### ISSUE TITLE
xl2tpd / centos7

### ISSUE THREAD

**Issue by Rico29** [xelerance/xl2tpd#102]
Hello,
I'm trying to setup xl2tpd as an LNS on centos7. I'm using epel repo's xl2tpd version (1.3.6) and freeradius3.

My problem is that I always have this messages in logs : 

> Mar 21 10:31:47 radlns xl2tpd: xl2tpd[2711]: Call established with 178.20.x.x, Local: 3334, Remote: 63825, Serial: -1048959125
> Plugin radius.so loaded.
> RADIUS plugin initialized.
> Mar 21 10:31:47 radlns pppd[3337]: Plugin radius.so loaded.
> Mar 21 10:31:47 radlns pppd[3337]: RADIUS plugin initialized.
> Plugin radattr.so loaded.
> RADATTR plugin initialized.
> Mar 21 10:31:47 radlns pppd[3337]: Plugin radattr.so loaded.
> Mar 21 10:31:47 radlns pppd[3337]: RADATTR plugin initialized.
> Plugin pppol2tp.so loaded.
> using channel 1
> Using interface ppp0
> Connect: ppp0 <-->
> Overriding mtu 1500 to 1460
> PPPoL2TP options: lnsmode tid 37837 sid 3334 debugmask 0
> Overriding mru 1500 to mtu value 1460
> sent [LCP ConfReq id=0x1 <mru 1420> <asyncmap 0x0> <auth chap MD5> <magic 0x7361788b>]
> Mar 21 10:31:47 radlns pppd[3337]: Plugin pppol2tp.so loaded.
> Mar 21 10:31:47 radlns pppd[3337]: pppd 2.4.5 started by root, uid 0
> Mar 21 10:31:47 radlns pppd[3337]: Using interface ppp0
> Mar 21 10:31:47 radlns pppd[3337]: Connect: ppp0 <-->
> Mar 21 10:31:47 radlns pppd[3337]: Overriding mtu 1500 to 1460
> Mar 21 10:31:47 radlns pppd[3337]: Overriding mru 1500 to mtu value 1460
> Mar 21 10:31:47 radlns systemd-udevd: Network interface NamePolicy= disabled on kernel command line, ignoring.
> Mar 21 10:31:47 radlns xl2tpd: xl2tpd[2711]: network_thread: recv packet from 178.20.x.x, size = 26, tunnel = 37837, call = 3334 ref=0 refhim=0
> Mar 21 10:31:47 radlns xl2tpd: xl2tpd[2711]: write_packet: tty is not open yet.
> Mar 21 10:31:47 radlns xl2tpd: xl2tpd[2711]: network_thread: bad packet
> Mar 21 10:31:47 radlns xl2tpd: xl2tpd[2711]: network_thread: recv packet from 178.20.x.x, size = 22, tunnel = 37837, call = 3334 ref=0 refhim=0
> Mar 21 10:31:47 radlns xl2tpd: xl2tpd[2711]: write_packet: tty is not open yet.
> Mar 21 10:31:47 radlns xl2tpd: xl2tpd[2711]: network_thread: bad packet

I guess the problem is that xl2tpd can not talk correctly to pppd.
Does anybody here know what to do ?

Regards,
Cédric

**Comment by mcr** [comment]
Rico29 <notifications@github.com> wrote:
    > Mar 21 10:31:47 radlns pppd[3337]: Plugin radattr.so loaded.
    > Mar 21 10:31:47 radlns pppd[3337]: RADATTR plugin initialized.
    > Plugin pppol2tp.so loaded.

So, this is loaded, but somehow the pppd is not being told where the actual
socket for the L2TP is.

    > Mar 21 10:31:47 radlns systemd-udevd: Network interface
    > NamePolicy= disabled on kernel command line, ignoring.

Is this relevant, I wonder.

    > Mar 21 10:31:47 radlns xl2tpd: xl2tpd[2711]: network_thread: recv
    > packet from 178.20.x.x, size = 26, tunnel = 37837, call = 3334
    > ref=0 refhim=0
    > Mar 21 10:31:47 radlns xl2tpd: xl2tpd[2711]: write_packet: tty is
    > not open yet.
    > Mar 21 10:31:47 radlns xl2tpd: xl2tpd[2711]: network_thread: bad
    > packet

xl2tpd should have opened a pty and told pppd about it.
I don't know  what further to suggest.


--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by Rico29** [comment]
so it's a bug of xl2tpd implementation in el7 ?

**Comment by Rico29** [comment]
Everything is working as expected on centos6. I guess xl2tpd on centos7 is broken.

**Comment by shussain** [comment]
@Rico29   I believe this issue has been released with newver version of xl2pd. Can you please confirm with 1.3.10

**Comment by Rico29** [comment]
Hello,
This post is more than one year old. I found another solution, so I won't be able to test it.
