### ISSUE TITLE
xl2tpd / pppd passive option

### ISSUE THREAD

**Issue by Rico29** [xelerance/xl2tpd#103]
Hello,
Is there a way to disable the "passive" option used by pppd when a ppp tunnel is brought up by xl2tpd ?

root@radlns1:/# ps -ef | grep pppd
root     11303 11137  0 Mar29 pts/1    00:00:00 /usr/sbin/pppd **passive** nodetach 185.x.y.z:0.0.0.0 refuse-pap auth require-chap name L2TPServerBE debug file /etc/ppp/options.xl2tpd.be /dev/pts/1

Regards,
Cédric

**Comment by rsa9000** [comment]
There are no way to disable this option via configuration file or command line option, since "passive" option hardcoded and appended unconditionally to pppd command line options list.
