### ISSUE TITLE
pppd[6541]: In file /var/run/nm-ppp-options.xl2tpd.6526: unrecognized option 'lock'

### ISSUE THREAD

**Issue by k-wax** [xelerance/xl2tpd#108]
arch linux

Apr 27 22:39:49 tp NetworkManager[304]: <info>  Starting VPN service 'l2tp'...
Apr 27 22:39:49 tp NetworkManager[304]: <info>  VPN service 'l2tp' started (org.freedesktop.NetworkManager.l2tp), PID 6526
Apr 27 22:39:49 tp NetworkManager[304]: <info>  VPN service 'l2tp' appeared; activating connections
Apr 27 22:39:49 tp NetworkManager[304]: <info>  VPN connection '*****' (ConnectInteractive) reply received.
Apr 27 22:39:49 tp NetworkManager[304]: ** Message: Use '*****' as a gateway
Apr 27 22:39:49 tp NetworkManager[304]: ** Message: Check port 1701
Apr 27 22:39:49 tp NetworkManager[304]: ** Message: ipsec enable flag: (null)
Apr 27 22:39:49 tp NetworkManager[304]: ** Message: xl2tpd started with pid 6528
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: setsockopt recvref[30]: Protocol not available
Apr 27 22:39:49 tp NetworkManager[304]: <info>  VPN plugin state changed: starting (3)
Apr 27 22:39:49 tp NetworkManager[304]: <info>  VPN connection '*****' (Connect) reply received.
Apr 27 22:39:49 tp kernel: PPP generic driver version 2.4.2
Apr 27 22:39:49 tp kernel: NET: Registered protocol family 24
Apr 27 22:39:49 tp kernel: l2tp_core: L2TP core driver, V2.0
Apr 27 22:39:49 tp kernel: l2tp_netlink: L2TP netlink interface
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: Using l2tp kernel support.
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: xl2tpd version xl2tpd-1.3.7 started on tp PID:6528
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: Forked by Scott Balmos and David Stipp, (C) 2001
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: Inherited by Jeff McAdams, (C) 2002
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: Listening on IP address 0.0.0.0, port 1701
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: Connecting to host *****, port 1701
Apr 27 22:39:49 tp kernel: l2tp_ppp: PPPoL2TP kernel driver, V2.0
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: Connection established to *****, 1701.  Local: 14756, Remote: 4193
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: Calling on tunnel 14756
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: Call established with *****, Local: 63939, Remote: 2685, Serial: 1
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: start_pppd: I'm running:
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: "/usr/sbin/pppd"
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: "plugin"
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: "pppol2tp.so"
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: "pppol2tp"
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: "7"
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: "passive"
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: "nodetach"
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: ":"
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: "name"
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: "********"
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: "file"
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: "/var/run/nm-ppp-options.xl2tpd.6526"
Apr 27 22:39:49 tp pppd[6541]: Plugin pppol2tp.so loaded.
Apr 27 22:39:49 tp pppd[6541]: In file /var/run/nm-ppp-options.xl2tpd.6526: unrecognized option 'lock'
Apr 27 22:39:49 tp NetworkManager[304]: /usr/sbin/pppd: In file /var/run/nm-ppp-options.xl2tpd.6526: unrecognized option 'lock'
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: child_handler : pppd exited for call 2685 with code 2
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: call_close: Call 63939 to ***** disconnected
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: Terminating pppd: sending TERM signal to pid 6541
Apr 27 22:39:49 tp NetworkManager[304]: xl2tpd[6528]: get_call: can't find call 63939 in tunnel 14756
Apr 27 22:39:59 tp NetworkManager[304]:  (ref=0/0)
Apr 27 22:39:59 tp NetworkManager[304]: ** (nm-l2tp-service:6526): WARNING **: pppd timeout. Looks like pppd didn't initialize 
Apr 27 22:39:59 tp NetworkManager[304]: <warn>  VPN plugin failed: unknown (7)
Apr 27 22:40:29 tp NetworkManager[304]: <warn>  VPN connection '*****' connect timeout exceeded.
Apr 27 22:40:29 tp NetworkManager[304]: (nm-l2tp-service:6526): GLib-CRITICAL **: Source ID 8 was not found when attempting to 
Apr 27 22:40:29 tp NetworkManager[304]: ** Message: Terminated l2tp daemon with PID 6528.
Apr 27 22:40:29 tp NetworkManager[304]: xl2tpd[6528]: death_handler: Fatal signal 15 received
Apr 27 22:40:29 tp NetworkManager[304]: xl2tpd[6528]: Connection 41931 closed to *****, port 1701 (Server closing)
Apr 27 22:40:29 tp NetworkManager[304]: ** (nm-l2tp-service:6526): WARNING **: xl2tpd exited with error code 1
Apr 27 22:43:29 tp NetworkManager[304]: <info>  VPN service 'l2tp' disappeared

**Comment by klevin** [comment]
Started seeing this on my system as well, after Arch Linux moved from v1.3.6 to v1.3.7. I've downgraded back to 1.3.6 in the mean time. Don't know if this is intentional, but a maintenance release seems like a bad time to start barfing up on config options that previously were ok.

**Comment by dkosovic** [comment]
The unrecognized option issue was introduce with xl2tpd commit https://github.com/xelerance/xl2tpd/commit/e140bb6a1ab846e4cf548f4dbcdca6a3604248c6 which reorganized how the options are passed to pppd.

**Comment by dkosovic** [comment]
I think the issue is with pppd, with xl2tpd-1.3.6, I don't see any lock file being created under /var/run/lock when the lock option is explicitly specified. With xl2tpd-1.3.7, I think it exposed similar broken logic in pppd for lock support, but exposed it differently.

**Comment by obadz** [comment]
Removing this line: https://github.com/seriyps/NetworkManager-l2tp/blob/807899f8b5c269a15e22b7a05cc52185de00840c/src/nm-l2tp-service.c#L1323

… seems to fix the problem.

**Comment by dkosovic** [comment]
NetworkManager-l2tp version 1.2.2 already includes the workaround ( https://github.com/nm-l2tp/network-manager-l2tp/commit/6f1f5f7851624e36a2e2986a8d8ce734dad16ad2 )

**Comment by obadz** [comment]
@dkosovic, oops, looks like we were using the wrong repo: https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/networking/network-manager/l2tp.nix#L10

New repo asks for `libnma`. Any ideas where that's bundled?

```
checking for GLIB... yes
checking for GTK... yes
checking for LIBNMA... no
configure: error: Package requirements (libnma >= 1.1.0) were not met:

No package 'libnma' found
```

**Comment by dkosovic** [comment]
NetworkManager-l2tp version 1.2.2 is intended for NetworkManager 1.2 (or 1.1) based Linux distributions.

I'm pretty sure you'll have more luck with NetworkManager-l2tp version 1.0.2 which is intended for NetworkManager 1.0  (or 0.9). I'm still maintaining the nm-1-0 branch.

note: NetworkManager and VPN plug-ins tend to use even numbers for stable releases and odd numbers for devel releases.

Unfortunately NetworkManager-l2tp version 1.0.2 doesn't have the xl2tpd-1.3.7 lock file workaround, but has many other backported fixes, so you'll need to continue to use your workaround for the time being.

I'll release a new version 1.0.4 with the workaround, but there are a few other minor fixes I want to incorporate before I do, so maybe in the next couple of days.

**Comment by dkosovic** [comment]
@obadz before I do a 1.0.4 tag, could you test building the nm-1-0 branch https://github.com/nm-l2tp/network-manager-l2tp/tree/nm-1-0 ?

As I track the changes to NetworkManager-pptp, the dependencies will be more or less the same as pptp.nix , i.e. need to add libsecret (but like before, don't need pptp, but do need xl2tpd and strongswan or libreswan).

The following line in l2tp.niix is now redundant as the code using the deprecated APIs has been removed :
```C
postConfigure = "sed 's/-Werror//g' -i Makefile */Makefile";
```

**Comment by obadz** [comment]
@dkosovic, I'm now working on upgrading nixos to https://github.com/NixOS/nixpkgs/pull/16412 :-)

**Comment by dkosovic** [comment]
@obadz, nice

**Comment by obadz** [comment]
Thanks for pointing out that we no longer need to strip `-Werror`. Seems to work indeed.

**Comment by obadz** [comment]
@dkosovic thanks for the time though. Looks like you're just commenting the one line so it should definitely work for other 1.0 users…
