### ISSUE TITLE
Possible wrong code semantics in child_handler() in xl2tpd.c

### ISSUE THREAD

**Issue by ac000** [xelerance/xl2tpd#113]
When compiling under Fedora 24 gcc (GCC) 6.1.1 20160621 (Red Hat 6.1.1-3) we get the following warning

xl2tpd.c: In function ‘child_handler’:
xl2tpd.c:278:18: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
                  if (!kernel_support)
                  ^~
xl2tpd.c:281:21: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
                     c->fd = -1;
                     ^

Indeed looking at the code in question we have (line numbers will be one out due to extra feature test macro define, pull request sent)

 278 #ifdef USE_KERNEL
 279                  if (!kernel_support)
 280 #endif
 281                     close (c->fd);
 282                     c->fd = -1;
 283                     /*
 284                      \* terminate tunnel and call loops, returning to the
 285                      \* for(;;) loop (and possibly get the next pid)
 286                      */
 287                     t = NULL;
 288                     break;
 289                 }
 290                 c = c->next;
 291             }

So if USE_KERNEL is defined we will have

```
    if (!kernel_support)
            close (c->fd);
    c->fd = -1;
    ...
```

otherwise we will have

```
    close (c->fd);
    c->fd = -1;
    ...
```

However I'm not sure what the actual intent here is...

Cheers,
Andrew

**Comment by shussain** [comment]
This has been fixed in xl2tpd 1.3.13
