### ISSUE TITLE
rpmlint 1.3.8 rpm

### ISSUE THREAD

**Issue by petrmalkov** [xelerance/xl2tpd#120]
https://kojipkgs.fedoraproject.org//packages/xl2tpd/1.3.8/1.fc26/src/xl2tpd-1.3.8-1.fc26.src.rpm

 in spec is said:
upstream isn't using proper names, we manually rename v-VERSION.tar.gz to xl2tpd-VERSION.tar.gz
Source0: https://github.com/xelerance/%{name}/archive/%{name}-%{version}.tar.gz

is it correct or should be used
Source0: https://github.com/xelerance/%{name}/archive/%{commit}/%{name}-%{commit}.tar.gz
?

I used mock to generate rpms for el7.centos
rpmlint xl2tpd.spec ../RPMS/xl2tpd*.rpm

xl2tpd.spec:54: W: setup-not-quiet
xl2tpd.spec: W: invalid-url Source0: https://github.com/xelerance/xl2tpd/archive/xl2tpd-1.3.8.tar.gz HTTP Error 404: Not Found
xl2tpd.src:54: W: setup-not-quiet
xl2tpd.src: W: invalid-url Source0: https://github.com/xelerance/xl2tpd/archive/xl2tpd-1.3.8.tar.gz HTTP Error 404: Not Found
xl2tpd.x86_64: W: incoherent-version-in-changelog 1.3.8-2 ['1.3.8-2.el7.centos', '1.3.8-2.centos']
xl2tpd.x86_64: W: only-non-binary-in-usr-lib
xl2tpd.x86_64: E: non-readable /etc/xl2tpd/l2tp-secrets 0600L
xl2tpd.x86_64: E: incorrect-fsf-address /usr/share/licenses/xl2tpd-1.3.8/LICENSE
xl2tpd.x86_64: E: non-readable /var/run/xl2tpd/l2tp-control 0600L
xl2tpd.x86_64: E: non-readable /etc/ppp/chap-secrets.sample 0600L
xl2tpd.x86_64: W: no-manual-page-for-binary xl2tpd-control
xl2tpd.x86_64: W: non-standard-dir-in-usr usr
3 packages and 1 specfiles checked; 4 errors, 8 warnings.

Please update LICENSE and xl2tpd-control manual-page

**Comment by shussain** [comment]
Hi,
  Thank you for the issue report.

  The correct Source0 should be: https://github.com/xelerance/xl2tpd/archive/v%{version}.tar.gz

  I have updated the LICENSE and made a pull request. Once someone else looks it over and approves it, it will be in the devel branch (which will be merged into master for the next release).

  As for the xl2tp-control man page, it is on my todo list and I am planning on having a short man page added before the 1.3.9 release (before February 11th).

Samir

**Comment by shussain** [comment]
Have added an initial xl2tpd-control man page to the devel branch.

**Comment by shussain** [comment]
Closing ticket since release 1.3.9 has come out
