### ISSUE TITLE
l2tp client,  low througput, how to improve it?

### ISSUE THREAD

**Issue by wuzh01** [xelerance/xl2tpd#124]
[pre-conditions]
1、xl2tpd run in openWRT;
2、xl2tpd version:   xl2tpd-1.3.6
[Test Steps]
Step1: Run the VPN of l2tp,no ipsec  in openWRT system.
Step2: Download some files to do speedtesting by FTP tools (Filezilla client) on VPN of l2tp;
 Step3:view the throughput;
[Result]
1、the speed only 2-5Mpbs, it is lower then PPTP (41Mbps)
[Expected Result]
1、how to improve the speed?

**Comment by dkosovic** [comment]
Use `rx bps` and `tx bps` in `xltpd.conf

A lot of examples use the following which is 10 times the default xl2tpd values :
```
tx bps = 100000000
rx bps = 100000000
```

**Comment by shussain** [comment]
Thank you for your help @dkosovic
