### ISSUE TITLE
Issues with Fedora's xl2tpd.spec in v1.3.9 release

### ISSUE THREAD

**Issue by dwiest** [xelerance/xl2tpd#127]
First of all thank you very much for providing the files needed to package xl2tpd for various systems.  Too many projects don't bother with this important step.

I just tried building v1.3.9 on an Amazon Linux host and wanted to report two problems with the Fedora spec file.

1.  Version is 1.3.8 instead of 1.3.9
2.  Under the %files section there's a reference to doc/rfc2661.txt, but this file is not present in the release distribution.

I noticed that the %changelog section hasn't been updated since 2008, is that intentional?

Also, why aren't checksums provided for downloads?

**Comment by shussain** [comment]
Hello,
  Thank you for your feedback. I have fixed the version and removed doc/rfc2661.txt in the master branch.

  When you mentioned downloads, do you mean the [xl2tpd release page](https://github.com/xelerance/xl2tpd/releases)?

**Comment by dwiest** [comment]
Yes, the xl2tpd release page.

**Comment by shussain** [comment]
@dwiest The release page is based on whatever a tag is created. Github generates the zip and tar.gz files.  I am not aware of any way to automatically generate checksums whenever I create a tag.

If there is a way to automatically generate it, could you please provide a link to the github help page or blog?

**Comment by dwiest** [comment]
@shussain I'm no Github expert, but this page on the Debian Wiki shows how to add a detached GPG signature (for example).  After creating the release go back and edit it then attach your signature/checksum/etc. as a binary file. 

https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by shussain** [comment]
Ahhh.. I see.

Yes, associating a gpg key would be a good idea. I am planning on releasing the next release with gpg signature as per Github's guide [on signing tags using gpg](https://help.github.com/articles/signing-tags-using-gpg/)

**Comment by shussain** [comment]
Done several releases with gpg signature as per Github's guide. Closing this issue.
