### ISSUE TITLE
setsockopt recvref[30]: Protocol not available

### ISSUE THREAD

**Issue by shadyhh** [xelerance/xl2tpd#131]
Whenever I start xl2tpd, i get this message 
```
setsockopt recvref[30]: Protocol not available
Using l2tpd kernel support.
```
What is this about? I want to make an L2TP connection with mschap-v2 connection with Strongswan + xl2tpd

**Comment by dkosovic** [comment]
If you are doing IPsec without KLIPSng, you get the "Protocol not available" message with xl2tpd.

Don't worry it is harmless.

**Comment by shussain** [comment]
thank you for your help @dkosovic
