### ISSUE TITLE
increase #define STRLEN 80 in file.h

### ISSUE THREAD

**Issue by dkosovic** [xelerance/xl2tpd#132]
`file.h` contains the following line:
```C
#define STRLEN 80               /* Length of a string */
```

and `l2tp.h` has the following :
```C
#define MAXSTRLEN 120           /* Maximum length of common strings */
```

With NetworkManager-l2tp I've started using NetworkManager interface UUIDs for filenames that are passed to xl2tpd, the following example filename will fit in the 80 char (79 char strlen) of xl2tpd :
* `/var/run/nm-l2tp-ppp-options-9f4f010a-daea-4aff-8a17-37646f353699`

but the following is too long and gets truncated:
* `/var/run/NetworkManager/nm-l2tp-ppp-options-9f4f010a-daea-4aff-8a17-37646f353699`

Could `STRLEN` in `file.h` be increased? Perhaps to 120 which is what the unreleated `MAXSTRLEN` is set to?

**Comment by shussain** [comment]
We could certainly increase the STRLEN but perhaps to 80 or 100. Would 100 characters be enough for using the Network Manger inferace's UUID?

**Comment by dkosovic** [comment]
I think a 100 chars will be enough.

Was trying to think of examples of what the longest length might be and think they would be the following (for some Linux distros that use `/usr/loval/var/run` instead of `/var/run`) :

91 chars :
`/usr/local/var/run/NetworkManager/nm-l2tp-ppp-options-9f4f010a-daea-4aff-8a17-37646f353699`

92 chars :
`/usr/local/var/run/network-manager/nm-l2tp-ppp-options-9f4f010a-daea-4aff-8a17-37646f353699`

**Comment by shussain** [comment]
Okay. I have added a commit (e83d0eeb6332857c1861c3b4186b4b590685db11) on devel branch.

Thank you for your feedback.
