### ISSUE TITLE
Gentoo xl2tpd-dnsretry.patch for xl2tpd.c back from 2010

### ISSUE THREAD

**Issue by TeeDizzle** [xelerance/xl2tpd#134]
As potential maintainer for the abandoned package xl2tpd on Gentoo I am
trying to clean up things and stumbled about a patch for Gentoo Bug
307489 back from 2010:

[https://gitweb.gentoo.org/repo/gentoo.git/tree/net-dialup/xl2tpd/files/xl2tpd-dnsretry.patch](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-dialup/xl2tpd/files/xl2tpd-dnsretry.patch)
[https://bugs.gentoo.org/show_bug.cgi?id=307489](https://bugs.gentoo.org/show_bug.cgi?id=307489)

 It seems still to be applicable and I can somehow
comprehend what it is doing, but I am curious why the patch never found
its way into the xl2tpd project itself. Since I can't speak russian I
can not follow the discussion on: 

[https://homenet.beeline.ru/index.php?/topic/192551-%D0%BF%D0%B0%D0%B4%D0%B0%D0%B5%D1%82-l2tp/#comment-1063626345](https://homenet.beeline.ru/index.php?/topic/192551-%D0%BF%D0%B0%D0%B4%D0%B0%D0%B5%D1%82-l2tp/#comment-1063626345)

In 2012 former maintainer darkside made a comment about that which has
lasted up to the latest ebuild version:

> The below patch is questionable. Why wasn't it submitted upstream? If
> it ever breaks, it will just be removed. -darkside 20120914

[https://gitweb.gentoo.org/repo/gentoo.git/tree/net-dialup/xl2tpd/xl2tpd-1.3.6.ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-dialup/xl2tpd/xl2tpd-1.3.6.ebuild)

Can anybody provide information if this is still needed or why it was not added to xl2tpd officially?

**Comment by shussain** [comment]
Thank you for reaching out and letting us know about the patch

I will look into the patch and get back to you later on this week or early next week (sorry about the delay but I am a bit busy)

**Comment by TeeDizzle** [comment]
No problem, same here. Thanks for leaving a short note. Looking forward to your evaluation.

**Comment by shussain** [comment]
I have looked over the commit. I am unsure if the code is necessary since calling gethostbyname() again when it fails the first time seems somewhat pointless. Yes, DNS is not always reliable but in a majority of cases, if it failed a first time, it will fail again unless the underlying issue (connectivity, access to a resolver, etc is addressed).

In addition, the commit will need to be re-factored inorder to take advantage of existing helper methods and code convention.

I am afraid I am inclined to reject this patch.

**Comment by TeeDizzle** [comment]
First of all: I am not neccessarily looking into the patch being integrated in xl2tpd, my main concern is to get clarity for the Gentoo ebuild. Since the original author of the patch for Gentoo has not given any response on the background to the given day I can not tell wether it is still needed anywhere around on Gentoo environments.

> I am unsure if the code is necessary since calling gethostbyname() again when it fails the first time seems somewhat pointless. Yes, DNS is not always reliable but in a majority of cases, if it failed a first time, it will fail again unless the underlying issue (connectivity, access to a resolver, etc is addressed).

Agreed - but how about a xl2tp client losing connection to the internet temporarily while the redial option is chosen to keep it retrying until connectivity comes back. Would the temporary DNS failure lead to an exit situation the redial option was meant to prevent?

**Comment by shussain** [comment]
Thank  you for the clarification.

In regards to your question,  if the DNS fails, xl2tpd will go to the next lac. The code won't necessarily exit but if there is no lac, then not much will happen. 

I agree that the commit is to deal with DNS hiccup but it is a bit separate from the original intention of the redial option which is for xl2tpd to redial if the call gets disconnected. The redial configuration was not meant for re-attempt if there is a DNS hiccup when initiating a connection.

**Comment by TeeDizzle** [comment]
> The code won't necessarily exit but if there is no lac, then not much will happen.

Could you please elaborate on this?

> The redial configuration was not meant for re-attempt if there is a DNS hiccup when initiating a connection.

Sure. But what you describe as DNS hickups will more likely indicate the internet connection being completely down. And the patch seems to address exactly this situation. 
If I chose the redial option for a connection, I would not expect it to be dropped in case the internet connection was down but to keep retrying to whatever extend specified (max redial).

I did some more research on this and among others google translated one of my original links (seems to be the origin of the patch):

[https://homenet.beeline.ru/index.php?/topic/192551-%D0%BF%D0%B0%D0%B4%D0%B0%D0%B5%D1%82-l2tp/#comment-1063626345](https://homenet.beeline.ru/index.php?/topic/192551-%D0%BF%D0%B0%D0%B4%D0%B0%D0%B5%D1%82-l2tp/#comment-1063626345)

There I could find the information, that the patch was not only added to Gentoo but also to Mandriva.

Furthermore it seems to also have found its way to OpenWRT:

[https://dev.openwrt.org/ticket/12583](https://dev.openwrt.org/ticket/12583)
[https://github.com/openwrt/packages/issues/1334](https://github.com/openwrt/packages/issues/1334)

I even discovered an open issue from 2014 at your own repository with exactly this patch proposed (unfortunately without any comment to it):

[https://github.com/xelerance/xl2tpd/issues/52](https://github.com/xelerance/xl2tpd/issues/52)

From all of the above I can not believe this patch does not have any relevance at all.

**Comment by shussain** [comment]
Fair point about the patch being relevant for some people.

I did not fully realize the use case of the patch was trying to address when gethostbyname would not be resolved for a semi-extended time.

**Comment by TeeDizzle** [comment]
Yeah it does make some sense and it does not seem to hurt. I say this without any further knowledge of the xl2tpd code though, that is up to you to judge ;)
As for Gentoo I would tend to keep the patch, it is optionally applied with a use flag there. It would of course make things easier on the long run if you integrated the patch upstream. Not only for us but possibly as well for others. It generally seems like a small improvement to me.

**Comment by sfionov** [comment]
I think the patch originates from behaviour of one popular Russian provider with L2TP in past (now they are migrating to "IPoE"). Its L2TP endpoint (tp.internet.beeline.ru) was being resolved only with LAN DNS servers, and to NXDOMAIN with L2TP connection's DNS servers and any with any public DNS server. Immediate reconnect could lead to unresolved name and stopping connection retries.

**Comment by alexl000** [comment]
This bug should be fixed. Reconnect does not work.

**Comment by Firefishy** [comment]
The "Host name lookup failed" lockup is annoying. I expected `redial = yes` to have kicked in.

**Comment by Firefishy** [comment]
Alternative patch is available here: https://dev.archive.openwrt.org/ticket/12583

**Comment by shussain** [comment]
Patch from openwrt added to [1.3.18dev branch](https://github.com/xelerance/xl2tpd/tree/1.3.18dev)
