### ISSUE TITLE
udp_xmit failed to client-ipaddr:1701 with err=-1:Operation not permitted

### ISSUE THREAD

**Issue by eppesuig** [xelerance/xl2tpd#14]
Hi,
I have an ipsec+xl2tpd server that does not work in some contexts. When it does not work, I find these messages in /var/log/syslog:

udp_xmit failed to client-ipaddr:1701 with err=-1:Operation not permitted

of course, client-ipaddr is my current address. Activating all possible debug, I have this complete log:

network_thread: recv packet from client-ipaddr, size = 102, tunnel = 0, call = 0 ref=0 refhim=0 
get_call: allocating new tunnel for host client-ipaddr, port 1701. 
handle_avps: handling avp's for tunnel 1838, call 0 
message_type_avp: message type 1 (Start-Control-Connection-Request) 
protocol_version_avp: peer is using version 1, revision 0. 
framing_caps_avp: supported peer frames: sync 
bearer_caps_avp: supported peer bearers: 
firmware_rev_avp: peer reports firmware version 1280 (0x0500) 
hostname_avp: peer reports hostname 'ramon-box' 
vendor_avp: peer reports vendor 'Microsoft' 
assigned_tunnel_avp: using peer's tunnel 14 
receive_window_size_avp: peer wants RWS of 8.  Will use flow control. 
control_finish: message type is Start-Control-Connection-Request(1).  Tunnel is 14, call is 0. 
control_finish: sending SCCRP 
udp_xmit failed to client-ipaddr:1701 with err=-1:Operation not permitted 
network_thread: recv packet from client-ipaddr, size = 102, tunnel = 0, call = 0 ref=0 refhim=0 
get_call: allocating new tunnel for host client-ipaddr, port 1701. 
handle_avps: handling avp's for tunnel 8494, call 0 
message_type_avp: message type 1 (Start-Control-Connection-Request) 
protocol_version_avp: peer is using version 1, revision 0. 
framing_caps_avp: supported peer frames: sync 
bearer_caps_avp: supported peer bearers: 
firmware_rev_avp: peer reports firmware version 1280 (0x0500) 
hostname_avp: peer reports hostname 'ramon-box' 
vendor_avp: peer reports vendor 'Microsoft' 
assigned_tunnel_avp: using peer's tunnel 14 
receive_window_size_avp: peer wants RWS of 8.  Will use flow control. 
control_finish: message type is Start-Control-Connection-Request(1).  Tunnel is 14, call is 0. 
control_finish: Peer requested tunnel 14 twice, ignoring second one. 
udp_xmit failed to client-ipaddr:1701 with err=-1:Operation not permitted 
build_fdset: closing down tunnel 8494 
network_thread: recv packet from client-ipaddr, size = 102, tunnel = 0, call = 0 ref=0 refhim=0 
get_call: allocating new tunnel for host client-ipaddr, port 1701. 
handle_avps: handling avp's for tunnel 49971, call 63262 
message_type_avp: message type 1 (Start-Control-Connection-Request) 
protocol_version_avp: peer is using version 1, revision 0. 
framing_caps_avp: supported peer frames: sync 
bearer_caps_avp: supported peer bearers: 
firmware_rev_avp: peer reports firmware version 1280 (0x0500) 
hostname_avp: peer reports hostname 'ramon-box' 
vendor_avp: peer reports vendor 'Microsoft' 
assigned_tunnel_avp: using peer's tunnel 14 
receive_window_size_avp: peer wants RWS of 8.  Will use flow control. 
control_finish: message type is Start-Control-Connection-Request(1).  Tunnel is 14, call is 0. 
control_finish: Peer requested tunnel 14 twice, ignoring second one. 
udp_xmit failed to client-ipaddr:1701 with err=-1:Operation not permitted 
build_fdset: closing down tunnel 49971 
network_thread: select timeout 
udp_xmit failed to client-ipaddr:1701 with err=-1:Operation not permitted 
network_thread: select timeout 
udp_xmit failed to client-ipaddr:1701 with err=-1:Operation not permitted 
network_thread: select timeout 
udp_xmit failed to client-ipaddr:1701 with err=-1:Operation not permitted 
network_thread: select timeout 
udp_xmit failed to client-ipaddr:1701 with err=-1:Operation not permitted 
network_thread: select timeout 
Maximum retries exceeded for tunnel 1838.  Closing. 
udp_xmit failed to client-ipaddr:1701 with err=-1:Operation not permitted 
Connection 14 closed to client-ipaddr, port 1701 (Timeout) 
network_thread: select timeout 
udp_xmit failed to client-ipaddr:1701 with err=-1:Operation not permitted 
network_thread: select timeout 
udp_xmit failed to client-ipaddr:1701 with err=-1:Operation not permitted 
network_thread: select timeout 
udp_xmit failed to client-ipaddr:1701 with err=-1:Operation not permitted 
network_thread: select timeout 
udp_xmit failed to client-ipaddr:1701 with err=-1:Operation not permitted 
network_thread: select timeout 
Unable to deliver closing message for tunnel 1838. Destroying anyway.

**Comment by leonsim** [comment]
I got the exactly same issue on Gentoo. @eppesuig have you resolved this?

**Comment by eppesuig** [comment]
@leonsim that was a test environment and we dismissed it without making it working.

**Comment by leonsim** [comment]
@eppesuig thanks, I guess I will find some time to dig this. If get any luck to resolve this, I will share you.

**Comment by P4z** [comment]
Hey,
experiencing just the same issue from time to time on EdgeRouter Pro running xl2tpd-1.3.6 on Vyatta v1.9.0.4901118.160804.1139, the [latest available release](https://www.ubnt.com/download/edgemax/edgerouter-pro/default/edgerouter-er-8erpro-8ep-r8-firmware-v190) at the moment.

Hope you guys fix this issue soon so it gets incorporated by the other vendors too.

**Comment by richman1000000** [comment]
hi!
did anyone found a whay to fix it?
I've this error
 udp_xmit failed to 80.241.35.34:1701 with err=-1:Network is unreachable
version  xl2tpd-1.3.10, Debian 9.3 amd64

**Comment by P4z** [comment]
@xelerance Could you be so kind to review this issue again, please?

**Comment by shussain** [comment]
@remik As far as I can see, your issue is different.  Do you find anything in the logs (after enabling debug)?

**Comment by richman1000000** [comment]
Hello!
I have found cause of it in my case.

enx00e04c534458 - outgoing interface receiving DHCP address
ppp0 - vpn interface

Because xl2tpd don't have option to choose outgoing interface specifying option **defaultroute** is specified in pppd configuration this error happens.
Can I somehow specify default interface for xl2tpd vpn packets?
