### ISSUE TITLE
Can I use this project to implement a connection with an L2TP IPsec server from an  android app?

### ISSUE THREAD

**Issue by Khsed4** [xelerance/xl2tpd#141]
I want to implement an L2TP IPsec VPN for Android and as I googled I have to make the connection with native (C, C++) for connecting the Android APP to the server.
Can the source code of this project useful for creating the connection from android APP?

**Comment by shussain** [comment]
There is already l2tp and ipsec VPN connection available on Android. But you can always create your own implementation.

Some of the source code might be useful.
