### ISSUE TITLE
Contains both server/client side code or NOT

### ISSUE THREAD

**Issue by top-master** [xelerance/xl2tpd#142]
I want to implement an L2TP IPsec VPN for Android: since xl2tp looks like it supports linux we want to make an android client of your code but my #1 question:
is your code made just for SERVER or does it contain CLIENT code for connecting to existing server ?

if not do you can recommend any open source linux or android client supporting and/or using xl2tpd

**Comment by dkosovic** [comment]
Android comes with an L2TP/IPsec client by default, you can find the source code from an earlier Android release here :
* https://android.googlesource.com/platform/frameworks/base.git/+/gingerbread/vpn/java/android/net/vpn/

It works fine with xl2tpd on the server side if xl2tpd is configured correctly. If you do a Google search, you'll find lots of example configurations.

You can also find a NetworkManager L2TP/IPsec client for linux that uses xl2tpd here:
* https://github.com/nm-l2tp/network-manager-l2tp

Most linux distributions provide the NetworkManager-l2tp and NetworkManager-l2tp-gnome packages (or  network-manager-l2tp and network-manager-l2tp-gnome packages)

**Comment by shussain** [comment]
Closing issue.

You may be able to use some of the code for yoru Android client. Although I should mention that there is alreadey an l2tp IPsec VPN available for most Android devices
