### ISSUE TITLE
xl2tpd how to determine to which tunnel the avp belongs

### ISSUE THREAD

**Issue by Yuri1970** [xelerance/xl2tpd#143]
Now this log data "handle_avps: handling avp's for tunnel NNNN" is not available

**Comment by shussain** [comment]
@Yuri1970 That is correct. We had commented it out. However, if you want to have ti displayed, you just have to uncomment   [the following lines](https://github.com/xelerance/xl2tpd/blob/030f8fe64a8055ce761f3de21897bb34767f33e3/avp.c#L1637-L1641)

**Comment by shussain** [comment]
closing ticket. Please create new issue or reopen if you have any followup questions
