### ISSUE TITLE
request a specific address

### ISSUE THREAD

**Issue by oopcode** [xelerance/xl2tpd#145]
Hi everyone!

I've got the following server config:

```
[lns default]
lac = 1.1.1.1-254.254.254.254
ip range = 10.0.5.50-10.0.5.254 
local ip = 10.0.5.1  
refuse chap = yes  
refuse pap = yes  
require authentication = yes  
name = some-server  
ppp debug = yes  
pppoptfile = /etc/ppp/options.xl2tpd  
length bit = yes
```

And the following client config:

```
[lac vpn-connection]
lns = <addr>
local ip = 10.0.5.55
ppp debug = yes
pppoptfile = /etc/ppp/options.l2tpd.client
length bit = yes
```

Documentation says that local ip in the lac section makes remote VPN server assign you a specific IP, in this case 10.0.5.55.

My problem is that this option is ignored: I always get the first unassigned address from the range (i.e., 10.0.5.50, 10.0.5.51, etc.)

Is this a bug, or am I doing something wrong?

**Comment by shussain** [comment]
The local ip is meant to be used in the LNS section.  It is not meant to be on the lac side.

**Comment by oopcode** [comment]
Huh. And there's no way to request a specific IP?
Sorry for asking this here, SO didn't help.

**Comment by shussain** [comment]
@oopcode You will likely need to use Radius as a means to assign IP addresses.
