### ISSUE TITLE
Require strongswan support

### ISSUE THREAD

**Issue by refrog2000** [xelerance/xl2tpd#151]
Dear @xelerance ,
<br />
I'm using your xl2tpd to set up a VPN based on L2TP/IPSEC when I found a problem: xl2tpd only support openswan for IPSEC support which is deleted from Debian source due to maintainer's lost contact. Please send someone for openswan maintain job or support other ipsec software or users will be forced to stop using xl2tpd due to lack of support for windows. 
<br />
Looking forwards to your reply.
<br />
refrog2000

**Comment by shussain** [comment]
@refrog2000 I am unsure what you mean by stronswan support. Is xl2tpd not working with your strongswan config? If so, can you please post it.

**Comment by refrog2000** [comment]
Dear maintainer,
<br />
In man page of xl2tpd.conf, it is clearly written in documents of attributes "ipsec saref" that your xl2tpd only support openswan with KILPS mast on
<br />
Yours
<br />
refrog2000

**Comment by shussain** [comment]
@refrog2000 Have you tried Strongswan with [connmark plugin](https://wiki.strongswan.org/projects/strongswan/wiki/Connmark)?

**Comment by refrog2000** [comment]
Dear maintainer,
<br />
Thank you. Close this issue as your wish.
<br />
Yours,
<br />
refrog2000
