### ISSUE TITLE
connection closes after a while

### ISSUE THREAD

**Issue by sameeralirock** [xelerance/xl2tpd#154]
I'm working on getting xl2tpd and ppp working to finish my VPN setup.
Right now ppp seems to disconnect shortly after the connection is started. I'm not sure what I'm missing at this point.

router output:
Code:

kaylee ~ # xl2tpd -D
xl2tpd[12108]: setsockopt recvref[30]: Protocol not available
xl2tpd[12108]: Using l2tp kernel support.
xl2tpd[12108]: xl2tpd version xl2tpd-1.3.1 started on kaylee PID:12108
xl2tpd[12108]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
xl2tpd[12108]: Forked by Scott Balmos and David Stipp, (C) 2001
xl2tpd[12108]: Inherited by Jeff McAdams, (C) 2002
xl2tpd[12108]: Forked again by Xelerance (www.xelerance.com) (C) 2006
xl2tpd[12108]: Listening on IP address 0.0.0.0, port 1701
xl2tpd[12108]: control_finish: Peer requested tunnel 61024 twice, ignoring second one.
xl2tpd[12108]: control_finish: Peer requested tunnel 61024 twice, ignoring second one.
xl2tpd[12108]: Connection established to 96.10.246.121, 1701.  Local: 45815, Remote: 61024 (ref=0/0).  LNS session is 'default'
xl2tpd[12108]: control_finish: Warning: Peer did not specify transmit speed
xl2tpd[12108]: start_pppd: I'm running: 
xl2tpd[12108]: "/usr/sbin/pppd" 
xl2tpd[12108]: "passive" 
xl2tpd[12108]: "nodetach" 
xl2tpd[12108]: "10.42.0.1:10.42.0.70" 
xl2tpd[12108]: "refuse-pap" 
xl2tpd[12108]: "auth" 
xl2tpd[12108]: "debug" 
xl2tpd[12108]: "file" 
xl2tpd[12108]: "/etc/ppp/options.xl2tpd" 
xl2tpd[12108]: "ipparam" 
xl2tpd[12108]: "96.10.246.121" 
xl2tpd[12108]: "plugin" 
xl2tpd[12108]: "pppol2tp.so" 
xl2tpd[12108]: "pppol2tp" 
xl2tpd[12108]: "7" 
xl2tpd[12108]: Call established with 96.10.246.121, Local: 48125, Remote: 20231, Serial: 1
xl2tpd[12108]: control_finish: Connection closed to 96.10.246.121, serial 1 ()
xl2tpd[12108]: Terminating pppd: sending TERM signal to pid 12109
xl2tpd[12108]: control_finish: Connection closed to 96.10.246.121, port 1701 (Server closing), Local: 45815, Remote: 61024

client output:
Code:

kaylee ~ # xl2tpd -D
xl2tpd[12108]: setsockopt recvref[30]: Protocol not available
xl2tpd[12108]: Using l2tp kernel support.
xl2tpd[12108]: xl2tpd version xl2tpd-1.3.1 started on kaylee PID:12108
xl2tpd[12108]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
xl2tpd[12108]: Forked by Scott Balmos and David Stipp, (C) 2001
xl2tpd[12108]: Inherited by Jeff McAdams, (C) 2002
xl2tpd[12108]: Forked again by Xelerance (www.xelerance.com) (C) 2006
xl2tpd[12108]: Listening on IP address 0.0.0.0, port 1701
xl2tpd[12108]: control_finish: Peer requested tunnel 61024 twice, ignoring second one.
xl2tpd[12108]: control_finish: Peer requested tunnel 61024 twice, ignoring second one.
xl2tpd[12108]: Connection established to 96.10.246.121, 1701.  Local: 45815, Remote: 61024 (ref=0/0).  LNS session is 'default'
xl2tpd[12108]: control_finish: Warning: Peer did not specify transmit speed
xl2tpd[12108]: start_pppd: I'm running: 
xl2tpd[12108]: "/usr/sbin/pppd" 
xl2tpd[12108]: "passive" 
xl2tpd[12108]: "nodetach" 
xl2tpd[12108]: "10.42.0.1:10.42.0.70" 
xl2tpd[12108]: "refuse-pap" 
xl2tpd[12108]: "auth" 
xl2tpd[12108]: "debug" 
xl2tpd[12108]: "file" 
xl2tpd[12108]: "/etc/ppp/options.xl2tpd" 
xl2tpd[12108]: "ipparam" 
xl2tpd[12108]: "96.10.246.121" 
xl2tpd[12108]: "plugin" 
xl2tpd[12108]: "pppol2tp.so" 
xl2tpd[12108]: "pppol2tp" 
xl2tpd[12108]: "7" 
xl2tpd[12108]: Call established with 96.10.246.121, Local: 48125, Remote: 20231, Serial: 1
xl2tpd[12108]: control_finish: Connection closed to 96.10.246.121, serial 1 ()
xl2tpd[12108]: Terminating pppd: sending TERM signal to pid 12109
xl2tpd[12108]: control_finish: Connection closed to 96.10.246.121, port 1701 (Server closing), Local: 45815, Remote: 61024

ppp options file:
Code:

ipcp-accept-local
ipcp-accept-remote
require-mschap-v2
ms-dns 10.42.0.1
#asyncmap 0
auth
mtu 1410
mru 1410
nodefaultroute
#crtscts
hide-password
lock
#modem
debug
name l2tpd
proxyarp
connect-delay 5000
#nomppe
lcp-echo-interval 30
lcp-echo-failure 5

**Comment by shussain** [comment]
@ sameeralirock You seem to be using xl2tpd 1.3.1  If so, that is almost 7 years old. 

Could you please try with xl2tpd 1.3.12 ?
