### ISSUE TITLE
Possible bug in pptpd and xl2tpd in Alpine

### ISSUE THREAD

**Issue by orbiran88** [xelerance/xl2tpd#155]
Hi, my xl2tpd with freeradius client and pptp on Alpine dist not working (I checked the settings on ubuntu and its working)
* Running in docker.

I got this log on the Alpine  docker:
```
xl2tpd[1]: start_pppd: I'm running:
xl2tpd[1]: "/usr/sbin/pppd"
xl2tpd[1]: "/dev/pts/1"
xl2tpd[1]: "passive"
xl2tpd[1]: "nodetach"
xl2tpd[1]: "10.0.12.1:10.0.12.101"
xl2tpd[1]: "refuse-pap"
xl2tpd[1]: "refuse-chap"
xl2tpd[1]: "auth"
xl2tpd[1]: "name"
xl2tpd[1]: "TEST"
xl2tpd[1]: "debug"
xl2tpd[1]: "file"
xl2tpd[1]: "/etc/ppp/options.xl2tpd"  
```
This line `xl2tpd[1]: "/dev/pts/1"` shows up right after `xl2tpd[1]: "/usr/sbin/pppd"` !
I saw in `ps` that by this log output the xl2tpd build the command line for /usr/sbin/pppd... and in this order the command is invalid!

This is a good order of pppd from Ubuntu:
```
Jul 29 22:13:21 lns01 xl2tpd[28016]: start_pppd: I'm running:
Jul 29 22:13:21 lns01 xl2tpd[28016]: "/usr/sbin/pppd"
Jul 29 22:13:21 lns01 xl2tpd[28016]: "passive"
Jul 29 22:13:21 lns01 xl2tpd[28016]: "nodetach"
Jul 29 22:13:21 lns01 xl2tpd[28016]: "10.0.12.1:10.0.12.101"
Jul 29 22:13:21 lns01 xl2tpd[28016]: "refuse-pap"
Jul 29 22:13:21 lns01 xl2tpd[28016]: "refuse-chap"
Jul 29 22:13:21 lns01 xl2tpd[28016]: "auth"
Jul 29 22:13:21 lns01 xl2tpd[28016]: "name"
Jul 29 22:13:21 lns01 xl2tpd[28016]: "TEST"
Jul 29 22:13:21 lns01 xl2tpd[28016]: "debug"
Jul 29 22:13:21 lns01 xl2tpd[28016]: "file"
Jul 29 22:13:21 lns01 xl2tpd[28016]: "/etc/ppp/options.xl2tpd"
Jul 29 22:13:21 lns01 xl2tpd[28016]: "/dev/pts/1"
```

What do you think? Bug?!

**Comment by orbiran88** [comment]
From docs:

> xl2tpd works by opening a pseudo-tty for communicating with pppd.
It runs completely in userspace but supports kernel mode L2TP.

**Comment by dkosovic** [comment]
Commit https://github.com/xelerance/xl2tpd/commit/e140bb6a1ab846e4cf548f4dbcdca6a3604248c6 reorganized how the arguments are passed to pppd.

So it depends on which version of xl2tpd you are using as to how the arguments are passed to pppd.
