### ISSUE TITLE
cannot establish connection

### ISSUE THREAD

**Issue by xbrs1** [xelerance/xl2tpd#157]
Hello guys,

I quite new to this topic and i have an issue, below the logs.
It seems that client does not accept IPCP conf sent by server.

Server logs:

>Sep 14 12:35:19 vsrv-bicab-1 systemd[1]: Started LSB: layer 2 tunelling protocol daemon.
Sep 14 12:35:28 vsrv-bicab-1 xl2tpd[31791]: network_thread: recv packet from 100.70.62.2, size = 109, tunnel = 0, call = 0 ref=0 refhim=0
Sep 14 12:35:28 vsrv-bicab-1 xl2tpd[31791]: get_call: allocating new tunnel for host 100.70.62.2, port 1701.
Sep 14 12:35:28 vsrv-bicab-1 xl2tpd[31791]: message_type_avp: message type 1 (Start-Control-Connection-Request)
Sep 14 12:35:28 vsrv-bicab-1 xl2tpd[31791]: protocol_version_avp: peer is using version 1, revision 0.
Sep 14 12:35:28 vsrv-bicab-1 xl2tpd[31791]: framing_caps_avp: supported peer frames: async sync
Sep 14 12:35:28 vsrv-bicab-1 xl2tpd[31791]: bearer_caps_avp: supported peer bearers:
Sep 14 12:35:28 vsrv-bicab-1 xl2tpd[31791]: firmware_rev_avp: peer reports firmware version 1680 (0x0690)
Sep 14 12:35:28 vsrv-bicab-1 xl2tpd[31791]: hostname_avp: peer reports hostname 'vsrv-bicab-2'
Sep 14 12:35:28 vsrv-bicab-1 xl2tpd[31791]: vendor_avp: peer reports vendor 'xelerance.com'
Sep 14 12:35:28 vsrv-bicab-1 xl2tpd[31791]: assigned_tunnel_avp: using peer's tunnel 35467
Sep 14 12:35:28 vsrv-bicab-1 xl2tpd[31791]: receive_window_size_avp: peer wants RWS of 4.  Will use flow control.
Sep 14 12:35:28 vsrv-bicab-1 xl2tpd[31791]: control_finish: message type is Start-Control-Connection-Request(1).  Tunnel is 35467, call is 0.
Sep 14 12:35:28 vsrv-bicab-1 xl2tpd[31791]: control_finish: sending SCCRP
Sep 14 12:35:29 vsrv-bicab-1 xl2tpd[31791]: network_thread: select timeout
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: network_thread: select timeout
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: network_thread: recv packet from 100.70.62.2, size = 12, tunnel = 47416, call = 0 ref=0 refhim=0
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: check_control: Received out of order control packet on tunnel 35467 (got 3, expected 1)
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: handle_packet: bad control packet!
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: network_thread: bad packet
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: network_thread: recv packet from 100.70.62.2, size = 20, tunnel = 47416, call = 0 ref=0 refhim=0
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: message_type_avp: message type 3 (Start-Control-Connection-Connected)
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: control_finish: message type is Start-Control-Connection-Connected(3).  Tunnel is 35467, call is 0.
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: Connection established to 100.70.62.2, 1701.  Local: 47416, Remote: 35467 (ref=0/0).  LNS session is 'L2TPserver'
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: network_thread: recv packet from 100.70.62.2, size = 48, tunnel = 47416, call = 0 ref=0 refhim=0
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: message_type_avp: message type 10 (Incoming-Call-Request)
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: message_type_avp: new incoming call
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: assigned_call_avp: using peer's call 2150
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: call_serno_avp: serial number is 1
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: bearer_type_avp: peer bears:digital
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: control_finish: message type is Incoming-Call-Request(10).  Tunnel is 35467, call is 0.
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: control_finish: Sending ICRP
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: network_thread: recv packet from 100.70.62.2, size = 50, tunnel = 47416, call = 19621 ref=0 refhim=0
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: message_type_avp: message type 12 (Incoming-Call-Connected)
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: tx_speed_avp: transmit baud rate is 0
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: frame_type_avp: peer uses:sync frames
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: rx_speed_avp: receive baud rate is 0
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: control_finish: message type is Incoming-Call-Connected(12).  Tunnel is 35467, call is 2150.
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: control_finish: Warning: Peer did not specify transmit speed
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: start_pppd: I'm running:
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: "/usr/sbin/pppd"
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: "plugin"
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: "pppol2tp.so"
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: "pppol2tp"
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: "7"
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: "pppol2tp_lns_mode"
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: "pppol2tp_tunnel_id"
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: "47416"
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: "pppol2tp_session_id"
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: "19621"
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: "passive"
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: "nodetach"
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: "192.168.231.1:192.168.231.2"
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: "refuse-pap"
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: "debug"
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: "file"
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: "/etc/ppp/options.xl2tpd"
Sep 14 12:35:31 vsrv-bicab-1 xl2tpd[31791]: Call established with 100.70.62.2, Local: 19621, Remote: 2150, Serial: 1
Sep 14 12:35:31 vsrv-bicab-1 pppd[31796]: Plugin pppol2tp.so loaded.
Sep 14 12:35:31 vsrv-bicab-1 pppd[31796]: pppd 2.4.7 started by root, uid 0
Sep 14 12:35:31 vsrv-bicab-1 pppd[31796]: using channel 326
Sep 14 12:35:31 vsrv-bicab-1 pppd[31796]: Using interface ppp0
Sep 14 12:35:31 vsrv-bicab-1 pppd[31796]: Connect: ppp0 <-->
Sep 14 12:35:31 vsrv-bicab-1 pppd[31796]: Overriding mtu 1500 to 1410
Sep 14 12:35:31 vsrv-bicab-1 pppd[31796]: PPPoL2TP options: lnsmode tid 47416 sid 19621 debugmask 0
Sep 14 12:35:31 vsrv-bicab-1 pppd[31796]: Overriding mru 1500 to mtu value 1410
Sep 14 12:35:31 vsrv-bicab-1 pppd[31796]: sent [LCP ConfReq id=0x1 <mru 1410> <asyncmap 0x0> <magic 0x248a68fc>]
Sep 14 12:35:31 vsrv-bicab-1 pppd[31796]: rcvd [LCP ConfReq id=0x1 <mru 1410> <asyncmap 0x0> <magic 0x9ff57084>]
Sep 14 12:35:31 vsrv-bicab-1 pppd[31796]: sent [LCP ConfAck id=0x1 <mru 1410> <asyncmap 0x0> <magic 0x9ff57084>]
Sep 14 12:35:31 vsrv-bicab-1 pppd[31796]: rcvd [LCP ConfAck id=0x1 <mru 1410> <asyncmap 0x0> <magic 0x248a68fc>]
Sep 14 12:35:31 vsrv-bicab-1 pppd[31796]: PPPoL2TP options: lnsmode tid 47416 sid 19621 debugmask 0
Sep 14 12:35:31 vsrv-bicab-1 pppd[31796]: sent [LCP EchoReq id=0x0 magic=0x248a68fc]
Sep 14 12:35:31 vsrv-bicab-1 pppd[31796]: sent [IPCP ConfReq id=0x1 <addr 192.168.231.1>]
Sep 14 12:35:32 vsrv-bicab-1 xl2tpd[31791]: network_thread: select timeout
Sep 14 12:35:34 vsrv-bicab-1 xl2tpd[31791]: network_thread: recv packet from 100.70.62.2, size = 50, tunnel = 47416, call = 19621 ref=0 refhim=0
Sep 14 12:35:34 vsrv-bicab-1 xl2tpd[31791]: check_control: Received out of order control packet on tunnel 35467 (got 3, expected 4)
Sep 14 12:35:34 vsrv-bicab-1 xl2tpd[31791]: handle_packet: bad control packet!
Sep 14 12:35:34 vsrv-bicab-1 xl2tpd[31791]: network_thread: bad packet
Sep 14 12:35:34 vsrv-bicab-1 pppd[31796]: rcvd [LCP ConfReq id=0x1 <mru 1410> <asyncmap 0x0> <magic 0x9ff57084>]
Sep 14 12:35:34 vsrv-bicab-1 pppd[31796]: Overriding mtu 1500 to 1410
Sep 14 12:35:34 vsrv-bicab-1 pppd[31796]: PPPoL2TP options: lnsmode tid 47416 sid 19621 debugmask 0
Sep 14 12:35:34 vsrv-bicab-1 pppd[31796]: Overriding mru 1500 to mtu value 1410
Sep 14 12:35:34 vsrv-bicab-1 pppd[31796]: sent [LCP ConfReq id=0x2 <mru 1410> <asyncmap 0x0> <magic 0x81873774>]
Sep 14 12:35:34 vsrv-bicab-1 pppd[31796]: sent [LCP ConfAck id=0x1 <mru 1410> <asyncmap 0x0> <magic 0x9ff57084>]
Sep 14 12:35:35 vsrv-bicab-1 xl2tpd[31791]: network_thread: select timeout
Sep 14 12:35:37 vsrv-bicab-1 pppd[31796]: rcvd [IPCP ConfReq id=0x1 <addr 10.9.21.191> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Sep 14 12:35:37 vsrv-bicab-1 pppd[31796]: Discarded non-LCP packet when LCP not open
Sep 14 12:35:40 vsrv-bicab-1 pppd[31796]: rcvd [IPCP ConfReq id=0x1 <addr 10.9.21.191> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Sep 14 12:35:40 vsrv-bicab-1 pppd[31796]: Discarded non-LCP packet when LCP not open

Client logs:

>Sep 14 12:35:28 vsrv-bicab-2 systemd[1]: Starting LSB: layer 2 tunelling protocol daemon...
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9985]: setsockopt recvref[30]: Protocol not available
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9985]: Using l2tp kernel support.
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9983]: Starting xl2tpd: xl2tpd.
Sep 14 12:35:28 vsrv-bicab-2 systemd[1]: Started LSB: layer 2 tunelling protocol daemon.
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: xl2tpd version xl2tpd-1.3.7 started on vsrv-bicab-2 PID:9986
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: Forked by Scott Balmos and David Stipp, (C) 2001
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: Inherited by Jeff McAdams, (C) 2002
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: Listening on IP address 0.0.0.0, port 1701
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: get_call: allocating new tunnel for host 100.80.1.252, port 1701.
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: Connecting to host 100.80.1.252, port 1701
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: control_finish: message type is (null)(0).  Tunnel is 0, call is 0.
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: control_finish: sending SCCRQ
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: network_thread: recv packet from 100.80.1.252, size = 109, tunnel = 35467, call = 0 ref=0 refhim=0
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: message_type_avp: message type 2 (Start-Control-Connection-Reply)
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: protocol_version_avp: peer is using version 1, revision 0.
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: framing_caps_avp: supported peer frames: async sync
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: bearer_caps_avp: supported peer bearers:
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: firmware_rev_avp: peer reports firmware version 1680 (0x0690)
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: hostname_avp: peer reports hostname 'vsrv-bicab-1'
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: vendor_avp: peer reports vendor 'xelerance.com'
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: assigned_tunnel_avp: using peer's tunnel 47416
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: receive_window_size_avp: peer wants RWS of 4.  Will use flow control.
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: control_finish: message type is Start-Control-Connection-Reply(2).  Tunnel is 47416, call is 0.
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: control_finish: sending SCCCN
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: Connection established to 100.80.1.252, 1701.  Local: 35467, Remote: 47416 (ref=0/0).
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: Calling on tunnel 35467
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: control_finish: message type is (null)(0).  Tunnel is 47416, call is 0.
Sep 14 12:35:28 vsrv-bicab-2 xl2tpd[9986]: control_finish: sending ICRQ
Sep 14 12:35:29 vsrv-bicab-2 xl2tpd[9986]: network_thread: select timeout
Sep 14 12:35:29 vsrv-bicab-2 xl2tpd[9986]: network_thread: select timeout
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: network_thread: recv packet from 100.80.1.252, size = 109, tunnel = 35467, call = 0 ref=0 refhim=0
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: check_control: Received out of order control packet on tunnel 47416 (got 0, expected 1)
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: handle_packet: bad control packet!
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: network_thread: bad packet
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: network_thread: recv packet from 100.80.1.252, size = 28, tunnel = 35467, call = 2150 ref=0 refhim=0
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: message_type_avp: message type 11 (Incoming-Call-Reply)
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: assigned_call_avp: using peer's call 19621
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: control_finish: message type is Incoming-Call-Reply(11).  Tunnel is 47416, call is 19621.
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: control_finish: Sending ICCN
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: Call established with 100.80.1.252, Local: 2150, Remote: 19621, Serial: 1 (ref=0/0)
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: start_pppd: I'm running:
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: "/usr/sbin/pppd"
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: "plugin"
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: "pppol2tp.so"
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: "pppol2tp"
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: "7"
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: "passive"
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: "nodetach"
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: ":"
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: "name"
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: "cpe"
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: "debug"
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: "file"
Sep 14 12:35:31 vsrv-bicab-2 xl2tpd[9986]: "/etc/ppp/options.xl2tpd.client"
Sep 14 12:35:31 vsrv-bicab-2 pppd[9991]: Plugin pppol2tp.so loaded.
Sep 14 12:35:31 vsrv-bicab-2 pppd[9991]: pppd 2.4.7 started by root, uid 0
Sep 14 12:35:31 vsrv-bicab-2 pppd[9991]: using channel 43
Sep 14 12:35:31 vsrv-bicab-2 pppd[9991]: Using interface ppp0
Sep 14 12:35:31 vsrv-bicab-2 pppd[9991]: Connect: ppp0 <-->
Sep 14 12:35:31 vsrv-bicab-2 pppd[9991]: Overriding mtu 1500 to 1410
Sep 14 12:35:31 vsrv-bicab-2 pppd[9991]: PPPoL2TP options: debugmask 0
Sep 14 12:35:31 vsrv-bicab-2 pppd[9991]: Overriding mru 1500 to mtu value 1410
Sep 14 12:35:31 vsrv-bicab-2 pppd[9991]: sent [LCP ConfReq id=0x1 <mru 1410> <asyncmap 0x0> <magic 0x9ff57084>]
Sep 14 12:35:31 vsrv-bicab-2 pppd[9991]: rcvd [LCP ConfReq id=0x1 <mru 1410> <asyncmap 0x0> <magic 0x248a68fc>]
Sep 14 12:35:31 vsrv-bicab-2 pppd[9991]: sent [LCP ConfAck id=0x1 <mru 1410> <asyncmap 0x0> <magic 0x248a68fc>]
Sep 14 12:35:32 vsrv-bicab-2 xl2tpd[9986]: network_thread: select timeout
Sep 14 12:35:34 vsrv-bicab-2 xl2tpd[9986]: network_thread: select timeout
Sep 14 12:35:34 vsrv-bicab-2 xl2tpd[9986]: network_thread: recv packet from 100.80.1.252, size = 12, tunnel = 35467, call = 2150 ref=0 refhim=0
Sep 14 12:35:34 vsrv-bicab-2 pppd[9991]: sent [LCP ConfReq id=0x1 <mru 1410> <asyncmap 0x0> <magic 0x9ff57084>]
Sep 14 12:35:34 vsrv-bicab-2 pppd[9991]: rcvd [LCP ConfReq id=0x2 <mru 1410> <asyncmap 0x0> <magic 0x81873774>]
Sep 14 12:35:34 vsrv-bicab-2 pppd[9991]: sent [LCP ConfAck id=0x2 <mru 1410> <asyncmap 0x0> <magic 0x81873774>]
Sep 14 12:35:34 vsrv-bicab-2 pppd[9991]: rcvd [LCP ConfAck id=0x1 <mru 1410> <asyncmap 0x0> <magic 0x9ff57084>]
Sep 14 12:35:34 vsrv-bicab-2 pppd[9991]: PPPoL2TP options: debugmask 0
Sep 14 12:35:34 vsrv-bicab-2 pppd[9991]: sent [IPCP ConfReq id=0x1 <addr 10.9.21.191> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Sep 14 12:35:35 vsrv-bicab-2 xl2tpd[9986]: network_thread: select timeout
Sep 14 12:35:37 vsrv-bicab-2 pppd[9991]: sent [IPCP ConfReq id=0x1 <addr 10.9.21.191> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Sep 14 12:35:38 vsrv-bicab-2 xl2tpd[9986]: network_thread: select timeout
Sep 14 12:35:40 vsrv-bicab-2 pppd[9991]: sent [IPCP ConfReq id=0x1 <addr 10.9.21.191> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]
Sep 14 12:35:42 vsrv-bicab-2 pppd[9991]: rcvd [LCP ConfReq id=0x2 <mru 1410> <asyncmap 0x0> <magic 0x81873774>]
Sep 14 12:35:42 vsrv-bicab-2 pppd[9991]: Overriding mtu 1500 to 1410
Sep 14 12:35:42 vsrv-bicab-2 pppd[9991]: PPPoL2TP options: debugmask 0
Sep 14 12:35:42 vsrv-bicab-2 pppd[9991]: Overriding mru 1500 to mtu value 1410
Sep 14 12:35:42 vsrv-bicab-2 pppd[9991]: sent [LCP ConfReq id=0x2 <mru 1410> <asyncmap 0x0> <magic 0x183d9c5c>]
Sep 14 12:35:42 vsrv-bicab-2 pppd[9991]: sent [LCP ConfAck id=0x2 <mru 1410> <asyncmap 0x0> <magic 0x81873774>]
Sep 14 12:35:45 vsrv-bicab-2 pppd[9991]: sent [LCP ConfReq id=0x2 <mru 1410> <asyncmap 0x0> <magic 0x183d9c5c>]
Sep 14 12:35:45 vsrv-bicab-2 pppd[9991]: rcvd [LCP ConfReq id=0x3 <mru 1410> <asyncmap 0x0> <magic 0x50b52c95>]
Sep 14 12:35:45 vsrv-bicab-2 pppd[9991]: sent [LCP ConfAck id=0x3 <mru 1410> <asyncmap 0x0> <magic 0x50b52c95>]
Sep 14 12:35:45 vsrv-bicab-2 pppd[9991]: rcvd [LCP ConfAck id=0x2 <mru 1410> <asyncmap 0x0> <magic 0x183d9c5c>]
Sep 14 12:35:45 vsrv-bicab-2 pppd[9991]: PPPoL2TP options: debugmask 0
Sep 14 12:35:45 vsrv-bicab-2 pppd[9991]: sent [IPCP ConfReq id=0x2 <addr 10.9.21.191> <ms-dns1 0.0.0.0> <ms-dns2 0.0.0.0>]

Client conf

>cat /etc/xl2tpd/xl2tpd.conf
[global]
access control = no
auth file = /etc/ppp/chap-secrets
debug avp = yes
debug network = yes
debug packet = yes
debug state = yes
debug tunnel = yes

>[lac L2TPserver]
;lns = 192.168.21.33
lns = 100.80.1.252
redial = yes
redial timeout = 5
require chap = no
require authentication = no
ppp debug = yes
pppoptfile = /etc/ppp/options.xl2tpd.client
require pap = no
autodial = yes
name = cpe
length bit = yes

Server conf:

>[global]
access control = yes
auth file = /etc/ppp/chap-secrets
debug avp = yes
debug network = yes
debug packet = yes
debug state = yes
debug tunnel = yes

>[lns L2TPserver]
ip range = 192.168.231.2-192.168.231.254
local ip = 192.168.231.1
require chap = no
refuse pap = yes
require authentication = no
ppp debug = yes
pppoptfile = /etc/ppp/options.xl2tpd
length bit = yes
;lac = 88.134.0.0 - 88.134.254.254
lac = 100.70.0.0 - 100.70.254.254

**Comment by shussain** [comment]
@xbrs1 Does this issue occur with xl2tpd 1.3.12?

**Comment by xbrs1** [comment]
I have tried to update xl2tpd but it says that is up-to-date.
Will give you more details on Monday.

**Comment by xbrs1** [comment]
apt-get install --only-upgrade xl2tpd
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
xl2tpd ist schon die neueste Version.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 185 nicht aktualisiert.

**Comment by shussain** [comment]
Yes, for your distro, you have the latest xl2tpd that has been packaged.

There have been more recent versions of xl2tpd released. Someone will have to create an xl2tpd package for your distro. 

However, you can get the [source code of more recent releases](https://github.com/xelerance/xl2tpd/releases) and compile xl2tpd (make clean; make; sudo make install).

You will have to uninstall your distro's xl2tpd package first.

**Comment by xbrs1** [comment]
Hi shussain,

As we are running on VMs, we want to change OS on the server and client machine.
Can you suggest which linux will be best to use ?

**Comment by xbrs1** [comment]
updated to 1.3.12 but see #160

**Comment by shussain** [comment]
Since you are now encountering issue #160, to simplify tracking, I will close this ticket.
