### ISSUE TITLE
xl2tpd times out when used with high bandwidth

### ISSUE THREAD

**Issue by xbrs1** [xelerance/xl2tpd#162]
Hello,

I have encountered a problem with xl2tpd version:  xl2tpd-1.3.12 used for high bandwidth traffic.
I'm using a server to generate UDP/TCP packets and send them thru l2tp, for the moment i can go up to 800MB/s but seems that xl2tpd times out after few seconds when I start to generate packets.

>Oct  4 11:16:50 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0x1 magic=0x2bd2f592]
Oct  4 11:16:50 vsrv-bicab-1u pppd[16801]: rcvd [LCP EchoRep id=0x1 magic=0x41b250fa]
Oct  4 11:17:00 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0x2 magic=0x2bd2f592]
Oct  4 11:17:00 vsrv-bicab-1u pppd[16801]: rcvd [LCP EchoRep id=0x2 magic=0x41b250fa]
Oct  4 11:17:01 vsrv-bicab-1u CRON[16842]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct  4 11:17:10 vsrv-bicab-1u pppd[16801]: rcvd [LCP EchoReq id=0x1 magic=0x41b250fa]
Oct  4 11:17:10 vsrv-bicab-1u pppd[16801]: sent [LCP EchoRep id=0x1 magic=0x2bd2f592]
Oct  4 11:17:10 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0x3 magic=0x2bd2f592]
Oct  4 11:17:10 vsrv-bicab-1u pppd[16801]: rcvd [LCP EchoRep id=0x3 magic=0x41b250fa]
Oct  4 11:17:20 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0x4 magic=0x2bd2f592]
Oct  4 11:17:20 vsrv-bicab-1u pppd[16801]: rcvd [LCP EchoRep id=0x4 magic=0x41b250fa]
Oct  4 11:17:30 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0x5 magic=0x2bd2f592]
Oct  4 11:17:30 vsrv-bicab-1u pppd[16801]: rcvd [LCP EchoRep id=0x5 magic=0x41b250fa]
Oct  4 11:17:40 vsrv-bicab-1u pppd[16801]: rcvd [LCP EchoReq id=0x2 magic=0x41b250fa]
Oct  4 11:17:40 vsrv-bicab-1u pppd[16801]: sent [LCP EchoRep id=0x2 magic=0x2bd2f592]
Oct  4 11:17:40 vsrv-bicab-1u xl2tpd[16778]: network_thread: select timeout
Oct  4 11:17:40 vsrv-bicab-1u xl2tpd[16778]: network_thread: recv packet from 100.70.62.35, size = 20, tunnel = 28121, call = 0 ref=0 refhim=0
Oct  4 11:17:40 vsrv-bicab-1u xl2tpd[16778]: message_type_avp: message type 6 (Hello)
Oct  4 11:17:40 vsrv-bicab-1u xl2tpd[16778]: control_finish: message type is Hello(6).  Tunnel is 27573, call is 0.
Oct  4 11:17:40 vsrv-bicab-1u xl2tpd[16778]: network_thread: recv packet from 100.70.62.35, size = 12, tunnel = 28121, call = 0 ref=0 refhim=0
Oct  4 11:17:40 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0x6 magic=0x2bd2f592]
Oct  4 11:17:40 vsrv-bicab-1u pppd[16801]: rcvd [LCP EchoRep id=0x6 magic=0x41b250fa]
Oct  4 11:17:41 vsrv-bicab-1u xl2tpd[16778]: network_thread: select timeout
Oct  4 11:17:50 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0x7 magic=0x2bd2f592]
Oct  4 11:17:50 vsrv-bicab-1u pppd[16801]: rcvd [LCP EchoRep id=0x7 magic=0x41b250fa]
Oct  4 11:18:00 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0x8 magic=0x2bd2f592]
Oct  4 11:18:00 vsrv-bicab-1u pppd[16801]: rcvd [LCP EchoRep id=0x8 magic=0x41b250fa]
Oct  4 11:18:10 vsrv-bicab-1u pppd[16801]: rcvd [LCP EchoReq id=0x3 magic=0x41b250fa]
Oct  4 11:18:10 vsrv-bicab-1u pppd[16801]: sent [LCP EchoRep id=0x3 magic=0x2bd2f592]
Oct  4 11:18:10 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0x9 magic=0x2bd2f592]
Oct  4 11:18:10 vsrv-bicab-1u pppd[16801]: rcvd [LCP EchoRep id=0x9 magic=0x41b250fa]
Oct  4 11:18:20 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0xa magic=0x2bd2f592]
Oct  4 11:18:20 vsrv-bicab-1u pppd[16801]: rcvd [LCP EchoRep id=0xa magic=0x41b250fa]
Oct  4 11:18:23 vsrv-bicab-1u kernel: [159187.724117] device ppp0 entered promiscuous mode
Oct  4 11:18:26 vsrv-bicab-1u kernel: [159190.827092] device ppp0 left promiscuous mode
Oct  4 11:18:30 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0xb magic=0x2bd2f592]
Oct  4 11:18:30 vsrv-bicab-1u pppd[16801]: rcvd [LCP EchoRep id=0xb magic=0x41b250fa]
Oct  4 11:18:40 vsrv-bicab-1u xl2tpd[16778]: network_thread: recv packet from 100.70.62.35, size = 20, tunnel = 28121, call = 0 ref=0 refhim=0
Oct  4 11:18:40 vsrv-bicab-1u xl2tpd[16778]: message_type_avp: message type 6 (Hello)
Oct  4 11:18:40 vsrv-bicab-1u xl2tpd[16778]: control_finish: message type is Hello(6).  Tunnel is 27573, call is 0.
Oct  4 11:18:40 vsrv-bicab-1u pppd[16801]: rcvd [LCP EchoReq id=0x4 magic=0x41b250fa]
Oct  4 11:18:40 vsrv-bicab-1u pppd[16801]: sent [LCP EchoRep id=0x4 magic=0x2bd2f592]
Oct  4 11:18:40 vsrv-bicab-1u xl2tpd[16778]: network_thread: recv packet from 100.70.62.35, size = 12, tunnel = 28121, call = 0 ref=0 refhim=0
Oct  4 11:18:40 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0xc magic=0x2bd2f592]
Oct  4 11:18:40 vsrv-bicab-1u pppd[16801]: rcvd [LCP EchoRep id=0xc magic=0x41b250fa]
Oct  4 11:18:41 vsrv-bicab-1u xl2tpd[16778]: network_thread: select timeout
Oct  4 11:18:50 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0xd magic=0x2bd2f592]
Oct  4 11:18:50 vsrv-bicab-1u pppd[16801]: rcvd [LCP EchoRep id=0xd magic=0x41b250fa]
Oct  4 11:18:58 vsrv-bicab-1u systemd-resolved[895]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Oct  4 11:18:59 vsrv-bicab-1u systemd-resolved[895]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Oct  4 11:19:00 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0xe magic=0x2bd2f592]
Oct  4 11:19:10 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0xf magic=0x2bd2f592]
Oct  4 11:19:20 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0x10 magic=0x2bd2f592]
Oct  4 11:19:30 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0x11 magic=0x2bd2f592]
Oct  4 11:19:40 vsrv-bicab-1u xl2tpd[16778]: network_thread: select timeout
Oct  4 11:19:40 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0x12 magic=0x2bd2f592]
Oct  4 11:19:41 vsrv-bicab-1u xl2tpd[16778]: network_thread: select timeout
Oct  4 11:19:47 vsrv-bicab-1u xl2tpd[16778]: message repeated 2 times: [ network_thread: select timeout]
Oct  4 11:19:50 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0x13 magic=0x2bd2f592]
Oct  4 11:19:55 vsrv-bicab-1u xl2tpd[16778]: network_thread: select timeout
Oct  4 11:20:00 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0x14 magic=0x2bd2f592]
Oct  4 11:20:10 vsrv-bicab-1u pppd[16801]: sent [LCP EchoReq id=0x15 magic=0x2bd2f592]
Oct  4 11:20:11 vsrv-bicab-1u xl2tpd[16778]: network_thread: select timeout
Oct  4 11:20:11 vsrv-bicab-1u xl2tpd[16778]: Maximum retries exceeded for tunnel 28121.  Closing.
Oct  4 11:20:11 vsrv-bicab-1u xl2tpd[16778]: Terminating pppd: sending TERM signal to pid 16801
Oct  4 11:20:11 vsrv-bicab-1u xl2tpd[16778]: Connection 27573 closed to 100.70.62.35, port 1701 (Timeout)
Oct  4 11:20:11 vsrv-bicab-1u pppd[16801]: Terminating on signal 15
Oct  4 11:20:11 vsrv-bicab-1u pppd[16801]: Connect time 3.6 minutes.
Oct  4 11:20:11 vsrv-bicab-1u pppd[16801]: Sent 2621979356 bytes, received 0 bytes.
Oct  4 11:20:11 vsrv-bicab-1u systemd-networkd[867]: ppp0: Lost carrier
Oct  4 11:20:11 vsrv-bicab-1u pppd[16801]: Script /etc/ppp/ip-down started (pid 16872)
Oct  4 11:20:11 vsrv-bicab-1u pppd[16801]: PPPoL2TP options: lnsmode tid 28121 sid 58033 debugmask 0
Oct  4 11:20:11 vsrv-bicab-1u pppd[16801]: sent [LCP TermReq id=0x2 "User request"]
Oct  4 11:20:11 vsrv-bicab-1u systemd[1]: Starting resolvconf-pull-resolved.service...
Oct  4 11:20:11 vsrv-bicab-1u pppd[16801]: Script /etc/ppp/ip-down finished (pid 16872), status = 0x0
Oct  4 11:20:11 vsrv-bicab-1u systemd[1]: Started resolvconf-pull-resolved.service.
Oct  4 11:20:11 vsrv-bicab-1u pppd[16801]: rcvd [LCP EchoReq id=0x5 magic=0x41b250fa]
Oct  4 11:20:11 vsrv-bicab-1u pppd[16801]: rcvd [LCP EchoReq id=0x6 magic=0x41b250fa]
Oct  4 11:20:11 vsrv-bicab-1u pppd[16801]: rcvd [LCP EchoReq id=0x7 magic=0x41b250fa]
Oct  4 11:20:11 vsrv-bicab-1u xl2tpd[16778]: network_thread: recv packet from 100.70.62.35, size = 20, tunnel = 28121, call = 0 ref=0 refhim=0
Oct  4 11:20:11 vsrv-bicab-1u pppd[16801]: rcvd [LCP TermReq id=0x2 "User request"]
Oct  4 11:20:11 vsrv-bicab-1u pppd[16801]: sent [LCP TermAck id=0x2]
Oct  4 11:20:11 vsrv-bicab-1u xl2tpd[16778]: message_type_avp: message type 6 (Hello)
Oct  4 11:20:11 vsrv-bicab-1u xl2tpd[16778]: control_finish: message type is Hello(6).  Tunnel is 27573, call is 0.
Oct  4 11:20:11 vsrv-bicab-1u pppd[16801]: rcvd [LCP TermAck id=0x2]
Oct  4 11:20:11 vsrv-bicab-1u pppd[16801]: Connection terminated.
Oct  4 11:20:11 vsrv-bicab-1u xl2tpd[16778]: network_thread: recv packet from 100.70.62.35, size = 12, tunnel = 28121, call = 0 ref=0 refhim=0
Oct  4 11:20:11 vsrv-bicab-1u xl2tpd[16778]: build_fdset: closing down tunnel 28121
Oct  4 11:20:11 vsrv-bicab-1u xl2tpd[16778]: network_thread: select returned error 9 (Bad file descriptor)
Oct  4 11:20:11 vsrv-bicab-1u systemd[1]: Starting resolvconf-pull-resolved.service...
Oct  4 11:20:11 vsrv-bicab-1u systemd[1]: Started resolvconf-pull-resolved.service.
Oct  4 11:20:11 vsrv-bicab-1u pppd[16801]: Exit.

Also check this picture with iftop on ppp0: https://imgur.com/a/CcsiCg2
If you guys can help me on how to enable some debug logging and maybe find the cause.

**Comment by shussain** [comment]
@xbrs1 I would suggest using _debug network_ in your xl2tpd.conf file

There is also _debug_tunnel_ and possibly _debug avp_, _debug packet_, and _debug state_ that you may find useful.

**Comment by shussain** [comment]
@xbrs1 Did that help? Can this issue be closed?

**Comment by xbrs1** [comment]
Hi Samir,
You can close the issue, i have decreased the bandwidth with 15%. Problem seems related to pppd.
