### ISSUE TITLE
Use of OTP for authentication fails

### ISSUE THREAD

**Issue by briantopping** [xelerance/xl2tpd#167]
Greetings, I am not sure exactly what's going on here, but PAM authentication over SSSD is failing when the user is set up to require an OTP token. I believe the situation is https://web.mit.edu/kerberos/krb5-1.13/doc/admin/otp.html must be used -- the authentication server logs state `Additional pre-authentication required` and then `Preauthentication failed` which is a common indicator of this.

As a baseline, when the user does not require OTP, the login succeeds. SSH can handle both the non-OTP and OTP users with a single concatenated password. 

I've tried with a few different PAM stacks to see if I could get around this, including the `sshd` stack to no avail. I don't know if I did it right though, I simply created a `/etc/pam.d/xl2tpd` stack. It may not even be the right name.

My environment is xl2tpd-1.3.13 on CentOS 7 after successful `ipa-client-install`. There are some references to this setup in https://libreswan.org/wiki/IKEv1_XAUTH_with_FreeOTP_and_FreeIPA and that code base should provide an example of the preauthentication handshake.

**Comment by briantopping** [comment]
I may have misinterpreted evidence here, closing for now and will reopen if I get new info...

**Comment by shussain** [comment]
Sounds good. Thanks
