### ISSUE TITLE
Xl2tpd with pppol2tp pppd plugin causes kernel faul !

### ISSUE THREAD

**Issue by CpServiceSpb** [xelerance/xl2tpd#178]
There is Ubuntu 14.04 x64 of 4.2.0-42-generic version with xl2tpd, pppd and pppl2tp plugin.
There is also dhcp wan interface what xl2tpd is connected via to internet prvoder using pppol2tp tunnel as a client.
When tunnel is established, pppol2tpd plugin is invoked, pppX interface is created and address is assigned to ppp interface.
It is the only one interface connected to Internet.
But after any internet activity as ping of some internet IP as for other one kernel fault is hsppened.
And only the server rebooting is helped.
I tried xl2tpd 1.3.6 version from repo as 1.3.13 built from sources also as pppd of 2.4.5 version from repo or 2.4.7 version built from sources.

One of bug messages:

`NMI watchdogL BUG: soft lockup - CPU#6 stuck for 22s ! [pppd:4051]`

And there are at kern.log:
```
Mar 22 08:40:59 Gate kernel: [  117.235976] show_signal_msg: 18 callbacks suppressed
Mar 22 08:40:59 Gate kernel: [  117.235982] xl2tpd[2929]: segfault at 4c ip 000000000040b32c sp 00007ffc3e5a9640 error 4 in xl2tpd[400000+18000]
```

Did someone solve the issue ?

**Comment by CpServiceSpb** [comment]
I reached the main reason of the issue.
It is somthing looks like routing cycling as I call this.
When xl2tpd works based on pppd launched and tunnel is established, and there is no necessary or right routing record on routing table, pppd causes the error which generates kernel bug.
Later I will post some links.
Now I use xl2tpd of 1.3.13 version with pppd of 2.4.7. version with the right routings.
And all works fine.

**Comment by shussain** [comment]
Good to hear @CpServiceSpb 

Since it is all working for you, closing this issue
