### ISSUE TITLE
Maximum retries exceeded for tunnel 32311.  Closing.

### ISSUE THREAD

**Issue by eppesuig** [xelerance/xl2tpd#179]
Hello,
I am trying to connect to a remote server via IPSec/L2TP. My client machine is a debian linux with stronswan U5.7.2/K4.19.0-4-amd64 and xl2tpd 1.3.12.
I configured the connection with ipsec and it seems to be working, in fact, its status is:

```Security Associations (1 up, 0 connecting):
L2TP-PSK-FOC[1]: ESTABLISHED 20 minutes ago, 192.168.245.99[192.168.245.99]...XXX.239.43.234[XXX.239.43.234]
L2TP-PSK-FOC{1}:  INSTALLED, TRANSPORT, reqid 1, ESP in UDP SPIs: c0c6016c_i cfa0cac0_o
L2TP-PSK-FOC{1}:   192.168.245.99/32[udp/l2f] === XXX.239.43.234/32[udp/l2f]
```

but, when I try to start the l2tp connection, I get these messages in syslog:

```apr 17 10:40:25 client xl2tpd[28658]: get_call: allocating new tunnel for host XXX.239.43.234, port 1701.
apr 17 10:40:25 client xl2tpd[28658]: Connecting to host XXX.239.43.234, port 1701
pr 17 10:40:25 client xl2tpd[28658]: control_finish: message type is (null)(0).  Tunnel is 0, call is 0.
apr 17 10:40:25 client xl2tpd[28658]: control_finish: sending SCCRQ
apr 17 10:40:26 client xl2tpd[28658]: network_thread: select timeout with max retries: 5 for tunnel: 32311
apr 17 10:40:28 client xl2tpd[28658]: network_thread: select timeout with max retries: 5 for > tunnel: 32311
apr 17 10:40:32 client xl2tpd[28658]: network_thread: select timeout with max retries: 5 for tunnel: 32311
apr 17 10:40:40 client xl2tpd[28658]: network_thread: select timeout with max retries: 5 for tunnel: 32311
apr 17 10:40:56 client xl2tpd[28658]: network_thread: select timeout with max retries: 5 for tunnel: 32311
apr 17 10:40:56 client xl2tpd[28658]: Maximum retries exceeded for tunnel 32311.  Closing.
apr 17 10:40:56 client xl2tpd[28658]: Connection 0 closed to 178.239.43.234, port 1701 (Timeout)
apr 17 10:40:57 client xl2tpd[28658]: network_thread: select timeout with max retries: 5 for tunnel: 32311
apr 17 10:40:59 client xl2tpd[28658]: network_thread: select timeout with max retries: 5 for tunnel: 32311
apr 17 10:41:03 client xl2tpd[28658]: network_thread: select timeout with max retries: 5 for tunnel: 32311
apr 17 10:41:11 client xl2tpd[28658]: network_thread: select timeout with max retries: 5 for tunnel: 32311
apr 17 10:41:27 client xl2tpd[28658]: network_thread: select timeout with max retries: 5 for tunnel: 32311
apr 17 10:41:27 client xl2tpd[28658]: Unable to deliver closing message for tunnel 32311. Destroying anyway.
```
How may I better investigate the problem?

Rhank you,
Giuseppe

**Comment by sunzd-handan** [comment]
I have the same problem

**Comment by gregrwm** [comment]
how was this resolved?  i'm having the same issue.  it works fine on my laptop, running lubuntu 20.04(focal), strongswan:amd64 (5.8.2-1ubuntu3.1, automatic), and xl2tpd:amd64 (1.3.12-1.1, automatic),

but fails with this very issue on my desktop, running ubuntu server 20.04(focal), with the very same strongswan and xl2tpd packages as my laptop, and with /etc/ipsec.conf, /etc/ipsec.secrets, /etc/xl2tpd/xl2tpd.conf, and /etc/ppp/options.l2tpd.client identical as on my laptop.  i tried disabling apparmor and rebooting, didn't help.

**Comment by TarikFadloul-lab** [comment]
Hi,
i'm facing the same issue, please let me know how did you get out of this issue?
many thanks
Tarik

**Comment by shussain** [comment]
Some people have reported a similar issue when using certain versions of Android. In those cases, it seemed to be related to some of hte phones not responding to L2TP keepalive heratbeats (please refer to issue  https://github.com/xelerance/xl2tpd/issues/191)

A possible work around is to use the max_retries option. Using "max retries" in the xl2tpd.conf (e.g. max retries = 100) has known to work for some users. Alternatively, another works around is to not to enable L2TP keepalive on the VPN servers.
