### ISSUE TITLE
No connection to Cisco ASA since 1.3.10, IP_PKTINFO is needed

### ISSUE THREAD

**Issue by shadyhh** [xelerance/xl2tpd#187]
I noticed that connections to Cisco ASA's don't work since 1.3.10 (other devices work!) because of a particular change in network.c. **Reverting this makes it working again: https://github.com/shadyhh/xl2tpd/commit/bafb5d7e0b03dc4a3aad16661e729d319b334405**

_Although I managed to fix it I'm not sure if the revert is the correct solution or if there is another answer to this problem._

We use xl2tpd together with strongswan, running on Debian 9.9.0 x64 with kernel Linux 4.9.0-9-amd64.

Here are the logs of the various tests I made. In all cases I could bring up the IPsec tunnel and even got an IP address after running `xl2tpd-control connect XXX`. The ultimate test was to ping a device within the remote subnet. This didn't work with Cisco ASA until reverting the mentioned change.
[asa-needs-IP_PKTINFO-breaks (ASA).log](https://github.com/xelerance/xl2tpd/files/3554178/asa-needs-IP_PKTINFO-breaks.ASA.log)
[asa-needs-IP_PKTINFO-works (no ASA).log](https://github.com/xelerance/xl2tpd/files/3554180/asa-needs-IP_PKTINFO-works.no.ASA.log)
[asa-needs-IP_PKTINFO-reverted-works.log](https://github.com/xelerance/xl2tpd/files/3554179/asa-needs-IP_PKTINFO-reverted-works.log)

xl2tpd.conf
```
[global]
; neccessary since 1.3.10 to make ASA connection work (in combination with above revert)
ipsec saref = yes
debug state = yes
debug network = yes
debug avp = yes
debug tunnel = yes
debug packet = yes

[lns default]
refuse chap = yes
refuse pap = yes
ppp debug = yes
length bit = yes
bps = 1000000

[lac XXX]
lns = XX.XX.XX.XX
pppoptfile = /etc/ppp/options.xl2tpd.XXX
```

/etc/ppp/options.xl2tpd.XXX
```
ipcp-accept-local
ipcp-accept-remote
refuse-eap
require-mschap-v2
noccp
noauth
idle 43200
nodefaultroute
mtu 1300
debug
connect-delay 5000
name XXX
password XXX
```

**Comment by odaken** [comment]
I also encountered this issue. Reverting v1.3.9 and disabling use of kernel module by  commenting out OSFLAGS+= -DUSE_KERNEL -D from Makefile resolves the issue.

**Comment by shadyhh** [comment]
Fixed (resp. reverted) in [v1.3.16](https://github.com/xelerance/xl2tpd/releases/tag/v1.3.16)
