### ISSUE TITLE
xl2tpd[27738]: L2TP kernel support not detected (try modprobing l2tp_ppp and pppol2tp)

### ISSUE THREAD

**Issue by zhangchunsheng** [xelerance/xl2tpd#188]
Amazon 2

xl2tpd[27738]: L2TP kernel support not detected (try modprobing l2tp_ppp and pppol2tp)

**Comment by emcepe** [comment]
eeh?

so try
        modprobe l2tp_ppp
or
        modprobe pppol2tp

**Comment by dkosovic** [comment]
xl2tp does `socket(AF_PPPOX, SOCK_DGRAM, PX_PROTO_OL2TP)` which is supposed to auto-load the l2tp_ppp kernel module :
* https://github.com/xelerance/xl2tpd/blob/master/network.c#L113

Which indirectly does the equivalent of  `modprobe net-l2tp-type-7` and that is what is broken, note that net-l2tp-type-7 is an alias of l2tp_ppp :
```
$ modinfo l2tp_ppp | grep alias
alias:          net-l2tp-type-7
alias:          net-pf-24-proto-1
```
e.g. on RHEL 8.1 and Fedora 31 where l2tp_ppp doesn't auto-load :
```
$ sudo modprobe net-l2tp-type-7

$ lsmod | grep l2tp
```

On Fedora 30 where it does auto-load:
```
$ sudo modprobe net-l2tp-type-7

$ lsmod | grep l2tp
l2tp_ppp               32768  0
l2tp_netlink           28672  1 l2tp_ppp
l2tp_core              36864  2 l2tp_ppp,l2tp_netlink
pppox                  16384  1 l2tp_ppp
ip6_udp_tunnel         16384  1 l2tp_core
udp_tunnel             16384  1 l2tp_core
ppp_generic            49152  2 pppox,l2tp_ppp

```

I submitted a bug for Fedora 31:
* https://bugzilla.redhat.com/show_bug.cgi?id=1794886

**Comment by dkosovic** [comment]
The following is an extract from _"Enhanced security of auto-loading kernel modules in RHEL 8 "_  web page (which requires a login to view) :
* https://access.redhat.com/articles/3760101

> To enhance Red Hat Enterprise Linux against possible future security vulnerabilities in lesser-known components which system administrators typically do not protect against, a set of kernel modules have been moved to the `kernel-modules-extra` package so they are not installed by default, and blacklisted by default so those components cannot be loaded by non-root users.
> 
> When a system requires use of one of these kernel modules, the system administrator must install the `kernel-modules-extra` package and explicitly remove the module blacklist.

Although the above was for RHEL8, it is also applicable to Fedora >= 31, CentOS 8 and other derivatives.

Note that on Fedora, RHEL and other derivatives, the  `kernel-modules-extra` package shouldn't need to be explicitly installed as the `xl2tpd` package has a package dependency on it.

The `/etc/modprobe.d/l2tp_netlink-blacklist.conf` file contains:
```sh
# Remove the blacklist by adding a comment # at the start of the line.
blacklist l2tp_netlink
```

The `/etc/modprobe.d/l2tp_ppp-blacklist.conf` file contains :
```sh
# Remove the blacklist by adding a comment # at the start of the line.
blacklist l2tp_ppp
```

To remove the blacklist of the L2TP modules by adding a # comment to the blacklist lines can be achieved with:
```
sudo sed -e '/blacklist sctp/s/^b/#b/g' -i /etc/modprobe.d/l2tp_netlink-blacklist.conf
sudo sed -e '/blacklist sctp/s/^b/#b/g' -i /etc/modprobe.d/l2tp_ppp-blacklist.conf
```

**Comment by shussain** [comment]
Thank you for your comment @dkosovic
