### ISSUE TITLE
Android 10 fails on Maximum retries exceeded for tunnel

### ISSUE THREAD

**Issue by reetp** [xelerance/xl2tpd#191]
I have been using xl2tpd 1.3.8 from EPEL on a CentOS box with Libreswan.

This has worked fine with Android versions up to v9.

With the release of Android v10 my S9 phone was upgraded, and since then it has proved impossible (for me at least) to get a continuous connection.

We have tested with 1.3.8 and 1.3.15 (rpm built from latest source)

We have tried various Android versions and configurations (with and without l2tp kernel support) and all seem OK, except v10.

The internet seems rammed with comments on the 'Maximum retries" issue, but no fixes.

There are a number of similar ones here, again with no resolution or ideas on how to debug this.

https://github.com/xelerance/xl2tpd/issues/32
https://github.com/xelerance/xl2tpd/issues/169
https://github.com/xelerance/xl2tpd/issues/179
https://github.com/xelerance/Openswan/issues/201

Some progress.

I discovered that 1.3.15 has some more options, notably max_retries (there are others if you look) :

https://github.com/xelerance/xl2tpd/blob/master/file.h

```
int max_retries;            /* Max retries before closing tunnel
                                   or stop re-transmitting */

```
I added that to xl2tpd.conf 

`max retries = 100`

At least now it doesn't stop every 1.5 minutes.

I still don't understand why it is getting stuck here or how to get around it. It looks like it has to be configuration somewhere but there are no clues as to how to find it or modify it :-(

Curious as to what this does as well - nothing but a short comment on it

` int cap_backoff;		/* Limit seconds between exponential backoff */`

Note - the Ipsec transport seems to be working perfectly.

I can post configs if required - they aren't anything out of the ordinary.

Any suggestion on how I can debug this further would be appreciated.

**Comment by reetp** [comment]
As a follow up my Android 10 has now been up for about 6 1/2 hours with no noticeable issues.

I have no idea what is going wrong, but the max retries gets it under control.

I may try and reduce that tomorrow.

**Comment by dkosovic** [comment]
I think it is a known Android L2TP issue with Android 9 & 10 not responding to the L2TP keepalive heartbeat (but not on all phones) :
* https://issuetracker.google.com/issues/118789580

The reported Android L2TP issues are blocked by the following issue which isn't publicly visible:
* https://issuetracker.google.com/issues/119076193

From the first Android issue tracker thread, a workaround seems to be to not enable L2TP keepalive on the VPN server. 

I think it is `lcp-echo-interval` and `lcp-echo-failure` PPP options that are responsible for the L2TP keepalive with xl2tpd. you could try commenting those PPP options if they are enabled.

Some phones have received an Android update with a L2TP connectivity fix.

**Comment by shussain** [comment]
Thank you @dkosovic and @reetp for reporting the issue and work-around. I have added them to the COMPATIBILITY_ISSUES file

**Comment by gr4yg00s3** [comment]
Hello, the assessment here seems to be inaccurate? I face this issue when attempting to connect from macOS and iOS. Also increasing the `max_retries` does not help, neither does commenting out `lcp-echo-interval` and `lcp-echo-failure`

Is there something else that I can try here?

**Comment by dkosovic** [comment]
Android uses mtpd for its L2TP implementation:
* https://android.googlesource.com/platform/external/mtpd/

the workarounds in this thread were for a mtpd regression bug introduced with Android 9 & 10.

Maximum retries exceeded can happen for a number of reasons, sorry I don't have any suggestions for iOS and macOS.

**Comment by dkosovic** [comment]
But if you are using a Linux distro that blacklists the L2TP kernel modules, you could try removing the blacklists :
* `/etc/modprobe.d/l2tp_netlink-blacklist.conf`
* `/etc/modprobe.d/l2tp_ppp-blacklist.conf`

**Comment by gr4yg00s3** [comment]
> Android uses mtpd for its L2TP implementation:
> 
> * https://android.googlesource.com/platform/external/mtpd/
> 
> the workarounds in this thread were for a mtpd regression bug introduced with Android 9 & 10.
> 
> Maximum retries exceeded can happen for a number of reasons, sorry I don't have any suggestions for iOS and macOS.

When I compare with openl2tpd (which works) in the pcap I see difference in the SCCRP I receive from the server. The bearer capabilities for analog and digital are set to false, could this cause some sort of issue?

From what I understand, the behavior is pretty odd. The control connection is connected (SCCN received by the peer), and even the incoming call is connected. Now during this establishment and after, xl2ptd seems to receive a control connection request for the established tunnel, and it ignores it saying "ignoring second one". When clean up occurs for these duplicate addresses it ends up reaping the originally established tunnel as well. (I'm still looking up the code to see if there is something I'm doing wrong)

**Comment by gr4yg00s3** [comment]
> But if you are using a Linux distro that blacklists the L2TP kernel modules, you could try removing the blacklists :
> 
> * `/etc/modprobe.d/l2tp_netlink-blacklist.conf`
> * `/etc/modprobe.d/l2tp_ppp-blacklist.conf`
 
This does not seem to be the issue 👍
