### ISSUE TITLE
xl2tpd many connections 

### ISSUE THREAD

**Issue by 8Loading8** [xelerance/xl2tpd#196]
Good day

I use xl2tpd-1.3.12

The number of connections became about 100 and speed problems started. There are no speed limits. Intel 10 Gb network card. Without VPN everything is fine with speed. VPN does not rise above 70 Mbps. If the number of connections is reduced, then pulls 100Mbps. Maybe there is some kind of buffer that needs to be increased?

**Comment by shussain** [comment]
xl2tpd does have an upper limit on the number of connections it can handle (~100 is the usual limit for most configurations). As such, the issue you are reporting does sound familiar.

There was [some experimental work done to increase the limit](https://github.com/xelerance/xl2tpd/tree/libevent). That branch still needs a bit more work (there some reports of crashes that need to be investigated) but you are more than welcome to review and provide pull requests for it.
