### ISSUE TITLE
the process of xl2tpd is  stop at “listening on ip address0.0.0.0，port 1701”

### ISSUE THREAD

**Issue by qirchseu** [xelerance/xl2tpd#197]
Hi.
I used two Linux PC to estabilsh a L2TP communication.  The Strongswan was configured to setup an IPSec VPN, which encrypted the communication. 
The xl2tpd server and client was configured by the "xl2tpd.conf". When the command "xl2tpd -D" was executed,  the logs on server and client were paused at " listening on ip address0.0.0.0，port 1701", and there's no more information posted in the log file. Is there any suggestion? Thank you.

**Comment by kiber-io** [comment]
Have you found a solution? I have the same problem, Ubuntu 20
