### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [xelerance/xl2tpd#199]
It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://docs.github.com/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by shussain** [comment]
Thank you for your suggestion. The Xelerance account is an organization (we had done it a while ago but I neglected to update this issue). As such closing this ticket.

**Comment by Neustradamus** [comment]
@shussain: Thanks for your reply and the change!

Can you update organization informations?
- https://github.com/xelerance

Change the name: Xelerance Github Account
Add website, and all other informations.

**Comment by Neustradamus** [comment]
@shussain: Have you seen my previous comment?

Can you update the organization informations?

The title is not good "GitHub Account"...

**Comment by shussain** [comment]
I am sorry, what do you propose the organization title be? It can not be renamed to xl2tpd or something like that. Would you want it to be just "Xelerance" ? 

With respect to website, that has been added.

**Comment by shussain** [comment]
Closing this ticket for now.

@Neustradamus  Please feel to update this issue or create a new issue if  you have anything else you would like changed

**Comment by Neustradamus** [comment]
@shussain: "Xelerance Github Account" is always in organization name, I think that you can change it.

**Comment by shussain** [comment]
Ah understood. That change has now been made.

**Comment by shussain** [comment]
Added a description and I did check and I am in the members page

**Comment by Neustradamus** [comment]
@shussain: You are not showed in public but in private, I do not see you.
And it is same for other team members...

You can add mail address, social links, etc.

You can select "Popular repositories" of your choice...
