### ISSUE TITLE
can I open multiple l2tp connection?

### ISSUE THREAD

**Issue by sunuslee** [xelerance/xl2tpd#21]
hi, i am using xl2tpd , which works fine.
after basic configure
i run xl2tpd and then get a working interface called ppp0.
my questions is, i have extra account and i want to make another  connection on my host(i guess it will give me extra bandwidth as well).
so, how can i get a ppp1 with different account? thank you!

my xl2tpd.conf:

[global]
access control = no
auth file = /etc/ppp/chap-secrets
debug avp = no
debug network = no
debug packet = no
debug state = yes
debug tunnel = no

[lac connection0]
lns = x.x.x.x
name = username
redial = yes
redial timeout = 5
require chap = yes
require authentication = yes
ppp debug = yes
pppoptfile = /etc/ppp/peers/connection0.l2tpd
require pap = yes
autodial = yes

/etc/ppp/peers/connection0.l2tpd
remotename connection0
user "username"
password "password"
unit 0
lock
nodeflate
nobsdcomp
noauth
persist
nopcomp
noaccomp
maxfail 5
debug

**Comment by freevest** [comment]
@tphelps 
Why I cant do this, I need help. My configuration is post at https://github.com/xelerance/xl2tpd/issues/123
