### ISSUE TITLE
xl2tpd 1.3.8 on raspbian stretch: terminates with log entry "child_handler : pppd exited for call ... with code 15"

### ISSUE THREAD

**Issue by michaelof** [xelerance/xl2tpd#222]
Need to connect to a ms windows based IPsec/L2TP vpn from Linux.
Final goal is to establish a RDP connection to a desktop "on the other side".
Windows to windows connectivity works at once, default settings. Stable. Verified with a temp. VM.
Tried from OpenSuse, with Network Manager, not even able to establish a L2TP connection.
Followed this archlinux guide https://wiki.archlinux.org/index.php/Openswan_L2TP/IPsec_VPN_client_setup to setup on a raspberry pi. 
Works at first, IPsec connection established, PPP device up, RDP connection could be established via xfreerdp.

ALWAYS after ~2 minutes, PPP device "dissappears". Even if there's traffic.
/var/log/daemon.log always shows 2 msgs then, e.g.:
```
Jan 26 01:18:21 hostname xl2tpd[8111]: child_handler : pppd exited for call 52796 with code 15
Jan 26 01:18:21 hostname xl2tpd[8111]: call_close: Call 51452 to xxx.xxx.xxx.xxx disconnected
```
Any hints would be great, if no bug but config issue.

**Comment by dkosovic** [comment]
For openSUSE with NetworkManager not able to establish a L2TP connection with Windows Server issue, you might need a patched or later version of pppd that accepts malformed PPP success packets from Windows Server:
* https://github.com/ppp-project/ppp/pull/156

For the Raspberry Pi there is not enough info as to what is happening with the SIGTERM (15) signal and pppd. You could try increasing the debugging.

**Comment by shussain** [comment]
It seems this issue is related to pppd version. As such closing this ticket.
