### ISSUE TITLE
How can i connect to cisco router L2TPv3 without IPSEC vpn using xl2tpd 

### ISSUE THREAD

**Issue by Mirkokrasic** [xelerance/xl2tpd#224]
Hello, 

Im trying to connect to our cisco router using l2tpv3 vpn without ipsec, using ubuntu client, and i found only doc about connecting xl2tpd with openswan using ipsec any help please ? 

Best regards

**Comment by shussain** [comment]
xl2tpd does not currently support L2TP version 3. As such the answer to your immediate question is no.

If you can use l2tpdv2, then you should be able to.
