### ISSUE TITLE
Upgrading 1.3.12 to 1.3.16 breaks VPN connection

### ISSUE THREAD

**Issue by chaostya** [xelerance/xl2tpd#230]
After upgrading to Ubuntu 22.04 package xl2tpd was upgraded from 1.3.12 to 1.3.16 and my L2TP/IPSEC connection stopped working.
Looks like xl2tpd incorrectly parses tunnel id from SCCRP message.

Attaching a file with 2 log snippets including hex packet dumps.
[xl2tpd_broken_tunnel_parsing_logs.txt](https://github.com/xelerance/xl2tpd/files/8010591/xl2tpd_broken_tunnel_parsing_logs.txt)

**Comment by chaostya** [comment]
building from source resolves the issue

**Comment by akarl10** [comment]
I played around with debuild and it turns out x2ltp does currently not work with lto (-flto=auto -ffat-lto-objects)
If I build x2ltp without this options it works as you said

**Comment by krrishh-org** [comment]
Facing this issue in Ubuntu 22.04 Jammy Jellyfish. Building from source is not an option. I would like to keep this issue open until it is resolved in Ubuntu Official repository.

**Comment by akarl10** [comment]
A better solution would be creating a new issue that tracks the lto incompatibility.
The only realistic downstream solution for Ubuntu is disabling lto in debian/rules
ex:
`dh_auto_build -- CFLAGS=" -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -O2 -Wall -DSANITY -DLINUX -I$(KERNELSRC)/include/ -DIP_ALLOCATION -DUSE_KERNEL $(shell **DEB_BUILD_MAINT_OPTIONS=optimize=-lto** dpkg-buildflags --get CFLAGS)" CPPFLAGS=" -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -O2 -Wall -DSANITY -DLINUX -I$(KERNELSRC)/include/ -DIP_ALLOCATION $(shell **DEB_BUILD_MAINT_OPTIONS=optimize=-lto** dpkg-buildflags --get CPPFLAGS)" LDFLAGS=" $(shell **DEB_BUILD_MAINT_OPTIONS=optimize=-lto** dpkg-buildflags --get LDFLAGS)"`

This is what I have done in my ppa

**Comment by akarl10** [comment]
If you are using Ubuntu 22.04 I would suggest trying out the workaround mentioned here
https://answers.launchpad.net/ubuntu/+question/701185
and here
https://bugs.launchpad.net/ubuntu/+source/xl2tpd/+bug/1951832

somehow a second bug report was opened. The second one has someone assigned, so I would suggest clicking "affects me" on this one:
https://bugs.launchpad.net/ubuntu/+source/xl2tpd/+bug/1968336

If you use network-manaer-l2tp the problem could be that that one uses l2tpd in /usr/sbin, but the one you compiled and installed is in /usr/local/sbin

probably a `make PREFIX=/usr install` fixes it

**Comment by akarl10** [comment]
FYI, I found the place where the issue happens if compiled with lto, but I don't fully understand why this happens.

in network.c function fix_hdr there is a struct payload_hdr. gcc seems to do some optimizations that result in making this method more like a nop. This can be workaround by making this struct volatile
`volatile struct payload_hdr *p = (struct payload_hdr *) buf;`

**Comment by crush2000** [comment]
> If you are using Ubuntu 22.04 I would suggest trying out the workaround mentioned here https://answers.launchpad.net/ubuntu/+question/701185 and here https://bugs.launchpad.net/ubuntu/+source/xl2tpd/+bug/1951832
> 
> somehow a second bug report was opened. The second one has someone assigned, so I would suggest clicking "affects me" on this one: https://bugs.launchpad.net/ubuntu/+source/xl2tpd/+bug/1968336
> 
> If you use network-manaer-l2tp the problem could be that that one uses l2tpd in /usr/sbin, but the one you compiled and installed is in /usr/local/sbin
> 
> probably a `make PREFIX=/usr install` fixes it

Still cant fix or workaround this problem. My journald looks like this now:

kwi 24 01:00:37 nm-l2tp-service[11368]: xl2tpd started with pid 11433
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: Not looking for kernel SAref support.
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: Using l2tp kernel support.
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: xl2tpd version xl2tpd-1.3.16 started on crushXnitro PID:11433
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: Forked by Scott Balmos and David Stipp, (C) 2001
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: Inherited by Jeff McAdams, (C) 2002
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: Listening on IP address 0.0.0.0, port 49636
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: Connecting to host X.X.X.X, port 1701
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: Connection established to X.X.X.X, 1701.  Local: 19994, Remote: 201 (ref=0/0).
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: Calling on tunnel 19994
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: Call established with X.X.X.X, Local: 65441, Remote: 142, Serial: 1 (ref=0/0)
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: start_pppd: I'm running:
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: "/usr/sbin/pppd"
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: "plugin"
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: "pppol2tp.so"
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: "pppol2tp"
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: "7"
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: "passive"
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: "nodetach"
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: ":"
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: "file"
kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: "/run/nm-l2tp-bd8ac49b-a2e9-4094-91dc-17a13ce61ec8/ppp-options"
kwi 24 01:00:37 pppd[11434]: Plugin pppol2tp.so loaded.
kwi 24 01:00:37 pppd[11434]: Plugin /usr/lib/pppd/2.4.9/nm-l2tp-pppd-plugin.so loaded.
kwi 24 01:00:37 pppd[11434]: pppd 2.4.9 started by root, uid 0
kwi 24 01:00:37 pppd[11434]: Using interface ppp0
kwi 24 01:00:37 pppd[11434]: Connect: ppp0 <-->
kwi 24 01:00:37 pppd[11434]: Overriding mtu 1500 to 1400
kwi 24 01:00:37 pppd[11434]: Overriding mru 1500 to mtu value 1400
kwi 24 01:00:37 NetworkManager[1017]: <info>  [1650754837.9839] manager: (ppp0): new Ppp device (/org/freedesktop/NetworkManager/Devices/6)
kwi 24 01:00:38 pppd[11434]: CHAP authentication succeeded
kwi 24 01:00:38 charon[11397]: 10[KNL] interface ppp0 activated
kwi 24 01:00:38 charon[11397]: 13[KNL] fe80::81ee:6717:6637:2084 appeared on ppp0
kwi 24 01:00:38 charon[11397]: 14[KNL] flags changed for fe80::81ee:6717:6637:2084 on ppp0
kwi 24 01:00:38 pppd[11434]: local  LL address fe80::81ee:6717:6637:2084
kwi 24 01:00:38 pppd[11434]: remote LL address fe80::0000:0000:00f0:0c0e
kwi 24 01:00:38 charon[11397]: 16[KNL] 192.168.57.181 appeared on ppp0
kwi 24 01:00:38 NetworkManager[1017]: <info>  [1650754838.0741] device (ppp0): state change: unmanaged -> unavailable (reason 'connection-assumed', sys-iface-state: 'external')
kwi 24 01:00:38 charon[11397]: 08[KNL] 192.168.57.181 disappeared from ppp0
kwi 24 01:00:38 charon[11397]: 10[KNL] 192.168.57.181 appeared on ppp0
kwi 24 01:00:38 NetworkManager[1017]: <info>  [1650754838.0751] device (ppp0): state change: unavailable -> disconnected (reason 'none', sys-iface-state: 'external')
kwi 24 01:00:38 pppd[11434]: local  IP address 192.168.57.181
kwi 24 01:00:38 pppd[11434]: remote IP address X.X.X.X
kwi 24 01:00:38 pppd[11434]: primary   DNS address 192.168.56.19
kwi 24 01:00:38 NetworkManager[1017]: <info>  [1650754838.0952] policy: set 'yyyyxyyyxyyyx' (ppp0) as default for IPv4 routing and DNS
kwi 24 01:01:03 charon[11397]: 12[IKE] sending keep alive to 91.X.63.182[4500]
kwi 24 01:01:23 charon[11397]: 15[IKE] sending keep alive to X.X.X.X[4500]
kwi 24 01:01:38 NetworkManager[11433]: xl2tpd[11433]: check_control: Received out of order control packet on tunnel 201 (got 2, expected 3)
kwi 24 01:01:38 NetworkManager[11433]: xl2tpd[11433]: handle_control: bad control packet!
kwi 24 01:01:40 NetworkManager[11433]: xl2tpd[11433]: check_control: Received out of order control packet on tunnel 201 (got 2, expected 3)
kwi 24 01:01:40 NetworkManager[11433]: xl2tpd[11433]: handle_control: bad control packet!
kwi 24 01:01:42 NetworkManager[11433]: xl2tpd[11433]: check_control: Received out of order control packet on tunnel 201 (got 2, expected 3)
kwi 24 01:01:42 NetworkManager[11433]: xl2tpd[11433]: handle_control: bad control packet!
kwi 24 01:01:43 charon[11397]: 07[IKE] sending keep alive to X.X.X.X[4500]
kwi 24 01:01:46 NetworkManager[11433]: xl2tpd[11433]: check_control: Received out of order control packet on tunnel 201 (got 2, expected 3)
kwi 24 01:01:46 NetworkManager[11433]: xl2tpd[11433]: handle_control: bad control packet!
kwi 24 01:01:54 NetworkManager[11433]: xl2tpd[11433]: check_control: Received out of order control packet on tunnel 201 (got 2, expected 3)
kwi 24 01:01:54 NetworkManager[11433]: xl2tpd[11433]: handle_control: bad control packet!
kwi 24 01:02:03 charon[11397]: 10[IKE] sending keep alive to X.X.X.X[4500]
kwi 24 01:02:08 NetworkManager[11433]: xl2tpd[11433]: Maximum retries exceeded for tunnel 19994.  Closing.
kwi 24 01:02:08 NetworkManager[11433]: xl2tpd[11433]: Terminating pppd: sending TERM signal to pid 11434
kwi 24 01:02:08 NetworkManager[11433]: xl2tpd[11433]: Connection 201 closed to X.X.X.X, port 1701 (Timeout)
kwi 24 01:02:08 pppd[11434]: Terminating on signal 15
kwi 24 01:02:08 pppd[11434]: Connect time 1.5 minutes.
kwi 24 01:02:08 pppd[11434]: Sent 3408418759 bytes, received 0 bytes.
kwi 24 01:02:08 charon[11397]: 13[KNL] 192.168.57.181 disappeared from ppp0
kwi 24 01:02:08 charon[11397]: 16[KNL] fe80::81ee:6717:6637:2084 disappeared from ppp0
kwi 24 01:02:08 charon[11397]: 06[KNL] interface ppp0 deactivated
kwi 24 01:02:08 NetworkManager[1017]: <info>  [1650754928.9942] device (ppp0): state change: disconnected -> unmanaged (reason 'connection-assumed', sys-iface-state: 'external')
kwi 24 01:02:09 pppd[11434]: Overriding mtu 1500 to 1400
kwi 24 01:02:09 pppd[11434]: Overriding mru 1500 to mtu value 1400
kwi 24 01:02:12 charon[11397]: 11[KNL] 192.168.57.181 appeared on ppp0
kwi 24 01:02:15 pppd[11434]: Connection terminated.
kwi 24 01:02:15 pppd[11434]: Connect time 1.5 minutes.
kwi 24 01:02:15 pppd[11434]: Sent 3408422107 bytes, received 0 bytes.
kwi 24 01:02:15 NetworkManager[11433]: xl2tpd[11433]: death_handler: Fatal signal 15 received
kwi 24 01:02:15 charon[11397]: 13[KNL] 192.168.57.181 disappeared from ppp0
kwi 24 01:02:15 charon[11397]: 14[KNL] interface ppp0 deleted
kwi 24 01:02:15 NetworkManager[11975]: Stopping strongSwan IPsec...
kwi 24 01:02:15 charon[11397]: 00[DMN] SIGINT received, shutting down
kwi 24 01:02:15 charon[11397]: 00[IKE] closing CHILD_SA bd8ac49b-a2e9-4094-91dc-17a13ce61ec8{1} with SPIs c99e9909_i (843 bytes) 09519760_o (3486181540 bytes) and TS 10.0.5.8/32[udp] === X.X.X.X/32[udp/l2f]
kwi 24 01:02:15 charon[11397]: 00[IKE] closing CHILD_SA bd8ac49b-a2e9-4094-91dc-17a13ce61ec8{1} with SPIs c99e9909_i (843 bytes) 09519760_o (3486181540 bytes) and TS 10.0.5.8/32[udp] === X.X.X.X/32[udp/l2f]
kwi 24 01:02:15 charon[11397]: 00[IKE] sending DELETE for ESP CHILD_SA with SPI c99e9909
kwi 24 01:02:15 charon[11397]: 00[ENC] generating INFORMATIONAL_V1 request 2999438773 [ HASH D ]
kwi 24 01:02:15 charon[11397]: 00[NET] sending packet: from 10.0.5.8[4500] to X.X.X.X[4500] (76 bytes)
kwi 24 01:02:15 charon[11397]: 00[IKE] deleting IKE_SA bd8ac49b-a2e9-4094-91dc-17a13ce61ec8[1] between 10.0.5.8[10.0.5.8]...X.X.X.X[X.X.X.X]
kwi 24 01:02:15 charon[11397]: 00[IKE] deleting IKE_SA bd8ac49b-a2e9-4094-91dc-17a13ce61ec8[1] between 10.0.5.8[10.0.5.8]...X.X.X.X[X.X.X.X]
kwi 24 01:02:15 charon[11397]: 00[IKE] sending DELETE for IKE_SA bd8ac49b-a2e9-4094-91dc-17a13ce61ec8[1]
kwi 24 01:02:15 charon[11397]: 00[ENC] generating INFORMATIONAL_V1 request 2417094363 [ HASH D ]
kwi 24 01:02:15 charon[11397]: 00[NET] sending packet: from 10.0.5.8[4500] to X.X.X.X[4500] (92 bytes)
kwi 24 01:02:15 ipsec_starter[11396]: child 11397 (charon) has quit (exit code 0)
kwi 24 01:02:15 ipsec_starter[11396]: 
kwi 24 01:02:15 ipsec_starter[11396]: charon stopped after 200 ms
kwi 24 01:02:15 ipsec_starter[11396]: ipsec starter stopped
kwi 24 01:02:15 pppd[11434]: Modem hangup
kwi 24 01:02:15 pppd[11434]: Exit.
kwi 24 01:02:15 nm-l2tp-service[11368]: ipsec shut down
kwi 24 01:02:15 NetworkManager[1017]: <info>  [1650754935.1179] policy: set 'Woloszyn-5G' (wlp9s0) as default for IPv4 routing and DNS
kwi 24 01:02:15 NetworkManager[1017]: <warn>  [1650754935.1424] dns-sd-resolved[89a44b1630a1bf13]: send-updates SetLinkDomains@5 failed: GDBus.Error:org.freedesktop.resolve1.NoSuchLink: Link 5 not known

**Comment by akarl10** [comment]
Your output suggest a different problem. is
`kwi 24 01:00:38 pppd[11434]: remote IP address X.X.X.X` the same as 
`kwi 24 01:00:37 NetworkManager[11433]: xl2tpd[11433]: Connecting to host X.X.X.X, port 1701`?

if so, do you also have access to the configuration of the l2tp server and are you able to change that?

I don't know if networkmanager/ppp supports having the ppp "inside" remote address the same as the "outside".
Networkmanager installs a route to the outside address with a low metric so that this one gets preferred over the default, but ppp installs a connected/link route to the same address that will always have a lower metric.

to test this you could try to type the following into the terminal immediatly after it connects:
`sudo ip r d X.X.X.X dev ppp0`

if that works, this is your "new" issue

**Comment by krrishh-org** [comment]
> I need some feedback on how to make it work until the bug will be solved. Building from source didn't solve this problem for me or i did something wrong. How to build from source to bypass this problem? l2tp with ipsec is mission critical for me.

@crush2000  Download xl2tpd v1.3.12-1.1 from here and use in Ubuntu 22.04 for now.
http://archive.ubuntu.com/ubuntu/pool/universe/x/xl2tpd/xl2tpd_1.3.12-1.1_amd64.deb

**Comment by akarl10** [comment]
@crush2000 you still did not confirm that in you case ppp peer ip and peer ip are the same, specifically if
```
kwi 24 01:01:23 charon[11397]: 15[IKE] sending keep alive to X.X.X.X[4500]
```
and
```
kwi 24 01:00:38 pppd[11434]: remote IP address X.X.X.X
```
are the same X.X.X.X

if so this is not the fault of xl2tpd.
If you still have access to a 20.04 system, could you, while connected print the output of
`ip r sh table 220`
`ip r`
`ip a`

for understanding your problem it is important to understand why now on 22.04 your routing gets messed up.
again: your log shows a working xl2tpd! A ppp session is created. This is also why downgrading/compiling yourself does not help you. The problem others where talking about was not even creating a l2tp tunnel that would transport the ppp session

**Comment by Vinicius-ufsc** [comment]
For those looking for a fast solution (worked for - Ubuntu 22.04.1 LTS) 

Just summarizing a solution mencioned above by akarl10, krrishh-org and others

1- Download:  xl2tpd_1.3.12-1.1_amd64.deb 
from https://ubuntu.pkgs.org/20.04/ubuntu-universe-amd64/xl2tpd_1.3.12-1.1_amd64.deb.html 

2- Go to the folder you have download the file and install the package with:  `sudo dpkg -i xl2tpd_1.3.12-1.1_amd64.deb`
you should see >> **dpkg: warning: downgrading xl2tpd from 1.3.16-1ubuntu0.1 to 1.3.12-1.1**

3- Make sure the version is now 1.3.12 running `xl2tpd --version`
you should see >> **xl2tpd version:  xl2tpd-1.3.12**

4- Reboot and try to connect your L2TP VPN

**Comment by dkosovic** [comment]
There is no need for those those workarounds any more with Ubuntu 22.04, just upgrade the xl2tpd package with the following:
```
sudo apt update
sudo apt upgrade xl2tpd
```

See the closed Ubuntu bug report for more details:
https://bugs.launchpad.net/ubuntu/+source/xl2tpd/+bug/1951832
