### ISSUE TITLE
xl2tpd fails when LTO is enabled

### ISSUE THREAD

**Issue by basak** [xelerance/xl2tpd#232]
Hi,

I'm working on #230 in Ubuntu. It looks like the underlying problem is that you're relying on some undefined C behaviour which happens to break when [LTO](https://wiki.ubuntu.com/ToolChain/LTO) is enabled. This is the case on Ubuntu 22.04. For example, it is reported that the following works around the issue:

```
--- xl2tpd-1.3.16.orig/network.c
+++ xl2tpd-1.3.16/network.c
@@ -159,7 +159,8 @@ static inline void fix_hdr (void *buf)
      * Fix the byte order of the header
      */
 
-    struct payload_hdr *p = (struct payload_hdr *) buf;
+    volatile struct payload_hdr *p = (struct payload_hdr *) buf;
+    
     _u16 ver = ntohs (p->ver);
     if (CTBIT (p->ver))
     {
```

I'm updating the package in Ubuntu 22.04 to build with LTO disabled. I'm filing this here because of what appears to be an underlying C bug in your code. Whatever is relying on undefined C behaviour needs fixing here, so it seems to me like there should be an issue open to track that here.

Thanks

**Comment by lzsiga** [comment]
Hi, I didn't test it, but I think some compilation warnings (that can be related with this problem) could be avoided by this change:

    --- control.corig       2022-05-20 20:14:53.334801573 +0200
    +++ control.c  2022-05-21 21:41:38.585944325 +0200
    @@ -1421,7 +1421,8 @@
          * check_payload() should already be called as a prerequisite.
          */
         struct payload_hdr *h = (struct payload_hdr *) (buf->start);
    -    _u16 *r = (_u16 *) h;       /* Nice to have raw word pointers */
    +    typedef _u16 __attribute__((aligned(1))) _u16_ua;
    +    _u16_ua *r= (_u16_ua *) h;       /* Nice to have raw word pointers */
         struct payload_hdr *new_hdr;
         int ehlen = 0;
         /*

**Comment by lzsiga** [comment]
@shussain
Sadly I cannot test if it solves the LTO-related problem, but at least it silences a compiler-warning. Should I create a Pull Request for it?

    control.orig.c:1424:5: warning: converting a packed 'struct payload_hdr' pointer (alignment 1) to a '_u16' {aka 'short unsigned int'} pointer (alignment 2) may result in an unaligned pointer value [-Waddress-of-packed-member]

**Comment by shussain** [comment]
> should I create a Pull Request for it?

Yes please.
