### ISSUE TITLE
Allow connections without IPSec

### ISSUE THREAD

**Issue by LoneRager117** [xelerance/xl2tpd#233]
I have used this script https://github.com/hwdsl2/setup-ipsec-vpn to setup a L2TP/IPSec VPN, but I have some clients that I want to allow to connect without using IPSec.  I have tried deleting these rules:
```
iptables -A INPUT -p udp --dport 1701 -m policy --dir in --pol ipsec -j ACCEPT
iptables -A INPUT -p udp --dport 1701 -j DROP
```
But they just come right back.  What am I missing here?  Thank you!

**Comment by shussain** [comment]
We dont' control the upstream documentation. xl2tpd does not require IPSec (although we strongly recommend having some kind of encryption). As such, closing this ticket.
