### ISSUE TITLE
Running into "write_packet: tty is not open yet" even though the 1024 max fd limit is not reached

### ISSUE THREAD

**Issue by gr4yg00s3** [xelerance/xl2tpd#234]
I'm trying to arrive at the max number of tunnels my xl2tpd based server can currently support. So far what I've observed is, xl2tpd starts out with 5 fds in use and then per client I see an increase by 2 fds. So presuming the fd limit is 1024, I should get close to 500 tunnels. But I seem to run into ```write_packet: tty is not open yet``` sometimes at ~350 tunnels and sometimes at around ~400 tunnels. Is there something I can do to see what might be going wrong?

**Comment by gr4yg00s3** [comment]
Thanks, I will take a look at this branch. 

A follow up question I had was, wouldn't the upper limit be consistent? Or is a variation in how many are eventually able to connect expected?

**Comment by shussain** [comment]
Are you asking more if the tunnels will be stable up to a certain point? Or if you will have some variance at the upper bound when using the same resources in terms of RAM/CPU, etc?

**Comment by shussain** [comment]
While the difference is a bit larger than I would expect, we did see some variance between the number of connections.

You can get more information with the custom  *--debug-signals* and
  *--debug-libevent* option (which is only in this branch) to see if you are having some errors or underlying issue.

**Comment by shussain** [comment]
Closing since I am assuming the debug outputs helped

**Comment by bob211314** [comment]
So how to solve this.
