### ISSUE TITLE
Multicast relay: lan <-> xl2tp clients !

### ISSUE THREAD

**Issue by CpServiceSpb** [xelerance/xl2tpd#240]
There is lan and xl2tp clients both connected to the same server.
I need that multicast would be relayed to both sides: from lan to l2tp clients and vice versa.
In particular WSD traffic: IP 239.255.255.250, ports 3702 and 5355

**Comment by dkosovic** [comment]
Sounds like something a WS-Discovery proxy can do, there are a number of implementations out there.

**Comment by CpServiceSpb** [comment]
Which ones ?
I use wsdd2 daemon from [https://github.com/Netgear/wsdd2] a little modified by Me to avoid this
[Issue 42](https://github.com/Netgear/wsdd2/issues/42)

**Comment by dkosovic** [comment]
xl2tpd doesn't support [RFC 4045](https://www.rfc-editor.org/rfc/rfc4045.html), which provides L2TP extensions to support efficient carrying of multicast traffic. That was the only reason I suggested a WS-Discovery proxy, I don't have any suggested as to which one.
