### ISSUE TITLE
Whether the folder permissions can be modified to 0644？

### ISSUE THREAD

**Issue by leeffo** [xelerance/xl2tpd#242]
https://github.com/xelerance/xl2tpd/blob/master/packaging/fedora/xl2tpd.spec#L65
![image](https://user-images.githubusercontent.com/47093973/184289045-02fbe0d2-3b24-4285-a0af-b3b5a77d2e28.png)

**Comment by dkosovic** [comment]
I think changing permissions from 755 (`rwxr-xr-x)` to 644 (`rw-r--r--`) on a directory makes no sense.

If `rw-r--r--` permissions were set for the `/run/xl2tpd/` (or `/var/run/xl2tpd/`) directory, then the xl2tpd process wouldn't be able read or write the contents of any file in that directory.

**Comment by dkosovic** [comment]
oh, I see, it's the named pipe under `/run/xl2tpd/` you are trying to protect, but not sure why?
```sh
$ ls -l /run/xl2tpd/l2tp-control
prw------- 1 root root 0 Oct 31 08:59 /run/xl2tpd/l2tp-control

$ file /run/xl2tpd/l2tp-control
/run/xl2tpd/l2tp-control: fifo (named pipe)
```

**Comment by leeffo** [comment]
> 我认为将目录的权限从 755 ( 更改`rwxr-xr-x)`为 644 ( ) 是没有意义的。`rw-r--r--`
> 
> 如果为（或）目录`rw-r--r--`设置了权限，则 xl2tpd 进程将无法读取或写入该目录中任何文件的内容。`/run/xl2tpd/``/var/run/xl2tpd/`

This is a hypothesis put forward to solve the problem at that time, because there was a problem with the operation of the i686 machine at that time, and it can be used normally by modifying the ko file later.
