### ISSUE TITLE
l2tp closes as soon as it established

### ISSUE THREAD

**Issue by RusselWestbrook6** [xelerance/xl2tpd#245]
Recently I had some problems when trying to connect using l2tp.
It looks like ms-dns doesn't allow to populate addresses for ipv6? why
![b jpeg](https://user-images.githubusercontent.com/62594994/185820027-c64216cc-e785-44c7-be3c-335b5b852ddb.png)
![a jpeg](https://user-images.githubusercontent.com/62594994/185820030-1f1edd20-eb86-48f8-b2b1-6429e178b16c.png)
?

**Comment by BooxXuan123** [comment]
OS: Centos linux 7(core)
Kernel version (if applicable): Linux 3.10.0-514.26.2.el7.x86_64
strongSwan version(s): Linux strongSwan U5.7.2/K3.10.0-514.26.2.el7.x86_64

**Comment by BooxXuan123** [comment]
get xl2tp by `yum install`

**Comment by ShixuanAE86** [comment]
@bartman

**Comment by gr4yg00s3** [comment]
The ms-dns options a pppd config option. It is meant to take only IPv4 Addresses. pppd (as per the RFC) is meant to bring up only a link-local v6 address on successful IPV6CP negotiation. A global v6 address is supposed to come from the endpoint you connect to via RAs over the PPP link (SLAAC/DHCPv6 whatever the endpoint chooses to implement) and the DNS is configured as part of that via the RDNSS option

**Comment by ShixuanAE86** [comment]
> 
Does the version affect this?
 my xl2tp version is v1.3.15
@gr4yg00s3

**Comment by ulysse31** [comment]
Hello ShixuanAE86 ^^

Please note that ipv6 is supported on my fork "as a standalone/dedicated service": it creates a new daemon called xl2tpd6, which listens to ipv6 address only, and will allow *inside ipv4 tunnel only*.
So a client will be able to open a tunnel in l2tp over ipv6, but inner tunnel (link to ppp for example) will still be ipv4.

I don't know your exact problematic, so I just wanted to clarify and know if this is what you need ^^' (on my case, it was ^^")

Regards,
