### ISSUE TITLE
<pcap-bpf.h> make: *** [Makefile:130: pfc] Error 1

### ISSUE THREAD

**Issue by V70024** [xelerance/xl2tpd#247]
<pre><font color="#AA0000">┌─[</font><font color="#FF5555"><b>root</b></font><font color="#FFFF55"><b>@</b></font><font color="#55FFFF"><b>id-531791</b></font><font color="#AA0000">]─[</font><font color="#00AA00">~</font><font color="#AA0000">]</font>
<font color="#AA0000">└──╼ </font><font color="#FFFF55"><b>#</b></font>cd xl2tpd/
<font color="#AA0000">┌─[</font><font color="#FF5555"><b>root</b></font><font color="#FFFF55"><b>@</b></font><font color="#55FFFF"><b>id-531791</b></font><font color="#AA0000">]─[</font><font color="#00AA00">~/xl2tpd</font><font color="#AA0000">]</font>
<font color="#AA0000">└──╼ </font><font color="#FFFF55"><b>#</b></font>make
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION -c contrib/pfc.c
<b>contrib/pfc.c:14:11:</b> <font color="#FF5555"><b>fatal error: </b></font>pcap-bpf.h: No such file or directory
   14 | # include <font color="#FF5555"><b>&lt;pcap-bpf.h&gt;</b></font>
      |           <font color="#FF5555"><b>^~~~~~~~~~~~</b></font>
compilation terminated.
make: *** [Makefile:130: pfc] Error 1
<font color="#AA0000">┌─[✗</font><font color="#AAAAAA">]─[</font><font color="#FF5555"><b>root</b></font><font color="#FFFF55"><b>@</b></font><font color="#55FFFF"><b>id-531791</b></font><font color="#AA0000">]─[</font><font color="#00AA00">~/xl2tpd</font><font color="#AA0000">]</font>
<font color="#AA0000">└──╼ </font><font color="#FFFF55"><b>#</b></font>

</pre>

**Comment by shussain** [comment]
What version of xl2tpd are you using and under what architecture?

**Comment by V70024** [comment]
I have not done any configuration
I just ran these commands

<pre><font color="#AA0000">┌─[</font><font color="#FF5555"><b>root</b></font><font color="#FFFF55"><b>@</b></font><font color="#55FFFF"><b>id-531791</b></font><font color="#AA0000">]─[</font><font color="#00AA00">~</font><font color="#AA0000">]</font>
<font color="#AA0000">└──╼ </font><font color="#FFFF55"><b>#</b></font>apt install xl2tpd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
xl2tpd is already the newest version (1.3.12-1.1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
<font color="#AA0000">┌─[</font><font color="#FF5555"><b>root</b></font><font color="#FFFF55"><b>@</b></font><font color="#55FFFF"><b>id-531791</b></font><font color="#AA0000">]─[</font><font color="#00AA00">~</font><font color="#AA0000">]</font>
<font color="#AA0000">└──╼ </font><font color="#FFFF55"><b>#</b></font>xl2tpd -v

xl2tpd version:  xl2tpd-1.3.12
<font color="#AA0000">┌─[✗</font><font color="#AAAAAA">]─[</font><font color="#FF5555"><b>root</b></font><font color="#FFFF55"><b>@</b></font><font color="#55FFFF"><b>id-531791</b></font><font color="#AA0000">]─[</font><font color="#00AA00">~</font><font color="#AA0000">]</font>
<font color="#AA0000">└──╼ </font><font color="#FFFF55"><b>#</b></font>git clone https://github.com/xelerance/xl2tpd.git 
Cloning into &apos;xl2tpd&apos;...
remote: Enumerating objects: 3344, done.
remote: Counting objects: 100% (220/220), done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 3344 (delta 126), reused 198 (delta 112), pack-reused 3124
Receiving objects: 100% (3344/3344), 1.37 MiB | 592.00 KiB/s, done.
Resolving deltas: 100% (2103/2103), done.
<font color="#AA0000">┌─[</font><font color="#FF5555"><b>root</b></font><font color="#FFFF55"><b>@</b></font><font color="#55FFFF"><b>id-531791</b></font><font color="#AA0000">]─[</font><font color="#00AA00">~</font><font color="#AA0000">]</font>
<font color="#AA0000">└──╼ </font><font color="#FFFF55"><b>#</b></font>cd xl2tpd/
<font color="#AA0000">┌─[</font><font color="#FF5555"><b>root</b></font><font color="#FFFF55"><b>@</b></font><font color="#55FFFF"><b>id-531791</b></font><font color="#AA0000">]─[</font><font color="#00AA00">~/xl2tpd</font><font color="#AA0000">]</font>
<font color="#AA0000">└──╼ </font><font color="#FFFF55"><b>#</b></font>make
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o xl2tpd.o xl2tpd.c
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o pty.o pty.c
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o misc.o misc.c
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o control.o control.c
<b>control.c:</b> In function ‘<b>expand_payload</b>’:
<b>control.c:1424:5:</b> <font color="#FF55FF"><b>warning: </b></font>converting a packed ‘<b>struct payload_hdr</b>’ pointer (alignment 1) to a ‘<b>_u16</b>’ {aka ‘<b>short unsigned int</b>’} pointer (alignment 2) may result in an unaligned pointer value [<font color="#FF55FF"><b>-Waddress-of-packed-member</b></font>]
 1424 |     <font color="#FF55FF"><b>_u16</b></font> *r = (_u16 *) h;       /* Nice to have raw word pointers */
      |     <font color="#FF55FF"><b>^~~~</b></font>
In file included from <b>control.c:23</b>:
<b>l2tp.h:95:8:</b> <font color="#55FFFF"><b>note: </b></font>defined here
   95 | struct <font color="#55FFFF"><b>payload_hdr</b></font>
      |        <font color="#55FFFF"><b>^~~~~~~~~~~</b></font>
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o avp.o avp.c
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o call.o call.c
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o network.o network.c
<b>network.c:</b> In function ‘<b>connect_pppol2tp</b>’:
<b>network.c:810:31:</b> <font color="#FF55FF"><b>warning: </b></font>converting a packed ‘<b>struct sockaddr_pppol2tp</b>’ pointer (alignment 1) to a ‘<b>const struct sockaddr</b>’ pointer (alignment 2) may result in an unaligned pointer value [<font color="#FF55FF"><b>-Waddress-of-packed-member</b></font>]
  810 |     if ((connect(fd2, (struct <font color="#FF55FF"><b>sockaddr</b></font> *)&amp;sax, sizeof(sax))) &lt; 0) {
      |                               <font color="#FF55FF"><b>^~~~~~~~</b></font>
In file included from <b>l2tp.h:263</b>,
                 from <b>network.c:29</b>:
<b>/usr/include/linux/if_pppox.h:79:8:</b> <font color="#55FFFF"><b>note: </b></font>defined here
   79 | struct <font color="#55FFFF"><b>sockaddr_pppol2tp</b></font> {
      |        <font color="#55FFFF"><b>^~~~~~~~~~~~~~~~~</b></font>
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o avpsend.o avpsend.c
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o scheduler.o scheduler.c
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o file.o file.c
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o aaa.o aaa.c
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o md5.o md5.c
cc  -o xl2tpd xl2tpd.o pty.o misc.o control.o avp.o call.o network.o avpsend.o scheduler.o file.o aaa.o md5.o 
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION -c contrib/pfc.c
<b>contrib/pfc.c:14:11:</b> <font color="#FF5555"><b>fatal error: </b></font>pcap-bpf.h: No such file or directory
   14 | # include <font color="#FF5555"><b>&lt;pcap-bpf.h&gt;</b></font>
      |           <font color="#FF5555"><b>^~~~~~~~~~~~</b></font>
compilation terminated.
make: *** [Makefile:130: pfc] Error 1
<font color="#AA0000">┌─[✗</font><font color="#AAAAAA">]─[</font><font color="#FF5555"><b>root</b></font><font color="#FFFF55"><b>@</b></font><font color="#55FFFF"><b>id-531791</b></font><font color="#AA0000">]─[</font><font color="#00AA00">~/xl2tpd</font><font color="#AA0000">]</font>
<font color="#AA0000">└──╼ </font><font color="#FFFF55"><b>#</b></font>
</pre>

**Comment by shussain** [comment]
I see you are running xl2tpd 1.3.12

What architecture are you running it on and what distro?

**Comment by V70024** [comment]
<pre><font color="#AA0000">┌─[</font><font color="#FF5555"><b>root</b></font><font color="#FFFF55"><b>@</b></font><font color="#55FFFF"><b>id-531791</b></font><font color="#AA0000">]─[</font><font color="#00AA00">~</font><font color="#AA0000">]</font>
<font color="#AA0000">└──╼ </font><font color="#FFFF55"><b>#</b></font>cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION=&quot;Ubuntu 20.04 LTS&quot;
PRETTY_NAME=&quot;Kali GNU/Linux Rolling&quot;
NAME=&quot;Kali GNU/Linux&quot;
ID=kali
VERSION=&quot;2022.2&quot;
VERSION_ID=&quot;2022.2&quot;
VERSION_CODENAME=&quot;kali-rolling&quot;
ID_LIKE=debian
ANSI_COLOR=&quot;1;31&quot;
HOME_URL=&quot;https://www.kali.org/&quot;
SUPPORT_URL=&quot;https://forums.kali.org/&quot;
BUG_REPORT_URL=&quot;https://bugs.kali.org/&quot;
</pre>

**Comment by V70024** [comment]
# ?

**Comment by shussain** [comment]
Have you got the following packages installed?
libpcap0.8
libpcap0.8-dev

**Comment by V70024** [comment]
I installed "libpcap0.8-dev".
This error occurred


<pre><font color="#AA0000">┌─[</font><font color="#FF5555"><b>root</b></font><font color="#FFFF55"><b>@</b></font><font color="#55FFFF"><b>id-531791</b></font><font color="#AA0000">]─[</font><font color="#00AA00">~/xl2tpd</font><font color="#AA0000">]</font>
<font color="#AA0000">└──╼ </font><font color="#FFFF55"><b>#</b></font>make
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o xl2tpd.o xl2tpd.c
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o pty.o pty.c
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o misc.o misc.c
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o control.o control.c
<b>control.c:</b> In function ‘<b>expand_payload</b>’:
<b>control.c:1424:5:</b> <font color="#FF55FF"><b>warning: </b></font>converting a packed ‘<b>struct payload_hdr</b>’ pointer (alignment 1) to a ‘<b>_u16</b>’ {aka ‘<b>short unsigned int</b><font color="#FF55FF"><b>’} pointer (alignment 2) may resul</b></font>t in an unaligned pointer value [<font color="#FF55FF"><b>-Waddress-of-packed-member</b></font>]
 1424 |     <font color="#FF55FF"><b>_u16</b></font> *r = (_u16 *) h;       /* Nice to have raw word pointers */
      |     <font color="#FF55FF"><b>^~~~</b></font>
In file included from <b>control.c:23</b>:
<b>l2tp.h:95:8:</b> <font color="#55FFFF"><b>note: </b></font>defined here
   95 | struct <font color="#55FFFF"><b>payload_hdr</b></font>
      |        <font color="#55FFFF"><b>^~~~~~~~~~~</b></font>
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o avp.o avp.c
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o call.o call.c
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o network.o network.c
<b>network.c:</b> In function ‘<b>connect_pppol2tp</b>’:
<b>network.c:810:31:</b> <font color="#FF55FF"><b>warning: </b></font>converting a packed ‘<b>struct sockaddr_pppol2tp</b>’ pointer (alignment 1) to a ‘<b>const struct sockaddr</b>’ pointer (alignment 2) may result in an unaligned pointer value [<font color="#FF55FF"><b>-Waddress-of-packed-member</b></font>]
  810 |     if ((connect(fd2, (struct <font color="#FF55FF"><b>sockaddr</b></font> *)&amp;sax, sizeof(sax))) &lt; 0) {
      |                               <font color="#FF55FF"><b>^~~~~~~~</b></font>
In file included from <b>l2tp.h:263</b>,
                 from <b>network.c:29</b>:
<b>/usr/include/linux/if_pppox.h:79:8:</b> <font color="#55FFFF"><b>note: </b></font>defined here
   79 | struct <font color="#55FFFF"><b>sockaddr_pppol2tp</b></font> {
      |        <font color="#55FFFF"><b>^~~~~~~~~~~~~~~~~</b></font>
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o avpsend.o avpsend.c
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o scheduler.o scheduler.c
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o file.o file.c
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o aaa.o aaa.c
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION   -c -o md5.o md5.c
cc  -o xl2tpd xl2tpd.o pty.o misc.o control.o avp.o call.o network.o avpsend.o scheduler.o file.o aaa.o md5.o 
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION -c contrib/pfc.c
cc  -o pfc pfc.o -lpcap 
cc -DDEBUG_PPPD -DTRUST_PPPD_TO_DIE -Os -Wall -Wextra -DSANITY -DLINUX -I./linux/include/ -DUSE_KERNEL -DIP_ALLOCATION  xl2tpd-control.c -o xl2tpd-control
<font color="#AA0000">┌─[</font><font color="#FF5555"><b>root</b></font><font color="#FFFF55"><b>@</b></font><font color="#55FFFF"><b>id-531791</b></font><font color="#AA0000">]─[</font><font color="#00AA00">~/xl2tpd</font><font color="#AA0000">]</font>
<font color="#AA0000">└──╼ </font><font color="#FFFF55"><b>#</b></font>
</pre>

**Comment by shussain** [comment]
I am sorry, where is the error? There is warnings but I don't see any error.

You should see an xl2tpd-control file in your xl2tpd directory. That would indicate that the code compiled.
