### ISSUE TITLE
Add Unit Tests for Key Functions of xl2tpd

### ISSUE THREAD

**Issue by shenhaicheng** [xelerance/xl2tpd#250]
Hi Team,
Currently，related test cases are black-box tests. We plan to add white-box tests to key functions of xl2tpd through the gtest framework. However, it needs to add the gtset framework code to the xl2tpd code. 

Is there a plan to add white-box tests? Would patches for this be welcome? Any suggestions or help would be much appreciated.

**Comment by shussain** [comment]
We have not used gtest. Ideally the unit tests would be in C and would test as much functionality as possible by invoking the appropriate function.

Having said that, PR are always welcome. We would review and provide feedback as appropriate

**Comment by shussain** [comment]
Closing this issue for now but feel free to make a PR anytime
