### ISSUE TITLE
Can I have multiple lns?

### ISSUE THREAD

**Issue by oferreiro** [xelerance/xl2tpd#30]
I using xl2tpd and works fine on my server.
But now I need separate two VPNs on the same server.
Is possible use multiple lns?
I am trying with config below:

[global]
debug network = yes
debug tunnel = yes
debug avp = yes
debug packet = yes
debug state = yes
access control = no
; port = 1701
; auth file = /etc/l2tpd/l2tp-secrets
; rand source = dev

[lns default]
name = employee.domain.com
ip range = 192.168.122.2-192.168.122.254
local ip = 192.168.122.1
exclusive = no
length bit = yes
refuse pap = yes
require authentication = yes
pppoptfile = /etc/ppp/options.l2tp. employee

[lns boss]
name = boss.domain.com
ip range = 192.168.0.220-192.168.0.254
local ip = 192.168.0.1
exclusive = no
length bit = yes
refuse pap = yes
require authentication = yes
pppoptfile = /etc/ppp/options.l2tp.boss

But it didn't work…

**Comment by tinyhare** [comment]
Use two xl2tpd daemon with separate configurations?

**Comment by tinyhare** [comment]
use lac option in lns context
; file xl2tpd.conf
[lns aaa]
lac = 192.168.1.1 - 192.168.1.10

[lns bbb]
lac = 192.168.1.11 - 192.168.1.20

[lns ccc]
lac = 192.168.1.21 - 192.168.1.30

if your lac use ip 192.168.1.15, it will connect to lns bbb

Here is the reason:
from the source code, you can find a function called get_lns()
`struct lns *get_lns (struct tunnel *t)
{
    /*
     * Look through our list of LNS's and
     * find a reasonable LNS for this call
     * if one is available
     */
    
    while (lns)
    {
        ipr = lns->lacs;
        while (ipr)
        {
            if ((ntohl (t->peer.sin_addr.s_addr) >= ntohl (ipr->start)) &&
                (ntohl (t->peer.sin_addr.s_addr) <= ntohl (ipr->end)))
            {
                allow = ipr->sense;
            }
            ipr = ipr->next;
        }
        if (allow)
            return lns;
}`

you can see that tunnel->peer.sin_addr.s_addr  will compare to  lns->lacs to select which lns be used.
