### ISSUE TITLE
client does not reconnect after server restart

### ISSUE THREAD

**Issue by atiertant** [xelerance/xl2tpd#40]
Hi,i got about 10 client that should connect to my server,if they do it one by per,this is ok,but after a server restart,all should reconnect but it's not working.
what could be the problem?

server side:

in /etc/ppp/options.xl2tpd

ipcp-accept-local
ipcp-accept-remote
refuse-eap
noccp
noauth
crtscts
mtu 1410
mru 1410
nodefaultroute
debug
lock
connect-delay 5000
name VPN
persist
maxfail 3

in /etc/xl2tpd/xl2tpd.conf

[global]
port = 1701
listen-addr = X.X.X.X

[lns default]
ip range = 10.0.1.2-10.0.1.254
local ip = 10.0.1.1
require chap = yes
refuse pap = yes
require authentication = yes
name = VPN
ppp debug = yes
pppoptfile = /etc/ppp/options.xl2tpd
length bit = yes

client side:

in /etc/ppp/options.xl2tpd.client

ipcp-accept-local
ipcp-accept-remote
refuse-eap
noccp
crtscts
mtu 1410
mru 1410
nodefaultroute
debug
lock
connect-delay 5000
name monlogin
password monmotdepasse
persist
maxfail 3

in /etc/xl2tpd/xl2tpd.conf 

[global]

[lac vpnserver]
lns = X.X.X.X
require chap = yes
refuse pap = yes
require authentication = yes
name = monlogin
ppp debug = yes
pppoptfile = /etc/ppp/options.xl2tpd.client
length bit = yes
redial = yes
redial timeout = 2
autodial = yes

logs server side:

Mar 27 09:31:17  daemon.notice xl2tpd[18296]: Maximum retries exceeded for tunnel 22743.  Closing.
Mar 27 09:31:17  daemon.info xl2tpd[18296]: Connection 24803 closed to X.X.X.X, port 1701 (Timeout)
Mar 27 09:31:17  daemon.debug xl2tpd[18296]: Unable to deliver closing message for tunnel 28337. Destroying anyway.
Mar 27 09:31:17  daemon.debug xl2tpd[18296]: control_finish: Peer requested tunnel 24803 twice, ignoring second one.
Mar 27 09:31:17  daemon.debug xl2tpd[18296]: control_finish: Peer requested tunnel 8262 twice, ignoring second one.
Mar 27 09:31:17  daemon.debug xl2tpd[18296]: check_control: Received out of order control packet on tunnel -1 (got 1, expected 0)
Mar 27 09:31:17  daemon.debug xl2tpd[18296]: handle_packet: bad control packet!
Mar 27 09:31:17  daemon.debug xl2tpd[18296]: check_control: Received out of order control packet on tunnel -1 (got 1, expected 0)
Mar 27 09:31:17  daemon.debug xl2tpd[18296]: handle_packet: bad control packet!
Mar 27 09:31:17  daemon.debug xl2tpd[18296]: check_control: Received out of order control packet on tunnel -1 (got 1, expected 0)
Mar 27 09:31:17  daemon.debug xl2tpd[18296]: handle_packet: bad control packet!
Mar 27 09:31:17  daemon.debug xl2tpd[18296]: check_control: Received out of order control packet on tunnel -1 (got 1, expected 0)
Mar 27 09:31:17  daemon.debug xl2tpd[18296]: handle_packet: bad control packet!
Mar 27 09:31:17  daemon.debug xl2tpd[18296]: check_control: Received out of order control packet on tunnel -1 (got 1, expected 0)
Mar 27 09:31:17  daemon.debug xl2tpd[18296]: handle_packet: bad control packet!
Mar 27 09:31:19  daemon.notice xl2tpd[18296]: Maximum retries exceeded for tunnel 64913.  Closing.
Mar 27 09:31:19  daemon.info xl2tpd[18296]: Connection 8262 closed to X.X.X.X, port 1701 (Timeout)
Mar 27 09:31:19  daemon.debug xl2tpd[18296]: Unable to deliver closing message for tunnel 15969. Destroying anyway.
Mar 27 09:31:19  daemon.debug xl2tpd[18296]: check_control: Received out of order control packet on tunnel -1 (got 1, expected 0)
Mar 27 09:31:19  daemon.debug xl2tpd[18296]: handle_packet: bad control packet!
Mar 27 09:31:21  daemon.notice xl2tpd[18296]: Maximum retries exceeded for tunnel 37782.  Closing.
Mar 27 09:31:21  daemon.info xl2tpd[18296]: Connection 37560 closed to X.X.X.X, port 1701 (Timeout)
Mar 27 09:31:21  daemon.debug xl2tpd[18296]: Unable to deliver closing message for tunnel 29917. Destroying anyway.
Mar 27 09:31:21  daemon.debug xl2tpd[18296]: control_finish: Peer requested tunnel 11055 twice, ignoring second one.
Mar 27 09:31:23  daemon.notice xl2tpd[18296]: Maximum retries exceeded for tunnel 18004.  Closing.
Mar 27 09:31:23  daemon.info xl2tpd[18296]: Connection 31020 closed to X.X.X.X, port 1701 (Timeout)
Mar 27 09:31:23  daemon.debug xl2tpd[18296]: Unable to deliver closing message for tunnel 62741. Destroying anyway.
Mar 27 09:31:23  daemon.debug xl2tpd[18296]: control_finish: Peer requested tunnel 13034 twice, ignoring second one.
Mar 27 09:31:23  daemon.debug xl2tpd[18296]: check_control: Received out of order control packet on tunnel -1 (got 3, expected 0)
Mar 27 09:31:23  daemon.debug xl2tpd[18296]: handle_packet: bad control packet!
Mar 27 09:31:25  daemon.notice xl2tpd[18296]: Maximum retries exceeded for tunnel 62216.  Closing.
Mar 27 09:31:25  daemon.info xl2tpd[18296]: Connection 9963 closed to X.X.X.X, port 1701 (Timeout)
Mar 27 09:31:25  daemon.debug xl2tpd[18296]: Unable to deliver closing message for tunnel 3411. Destroying anyway.
Mar 27 09:31:25  daemon.debug xl2tpd[18296]: check_control: Received out of order control packet on tunnel -1 (got 1, expected 0)
Mar 27 09:31:25  daemon.debug xl2tpd[18296]: handle_packet: bad control packet!
Mar 27 09:31:25  daemon.debug xl2tpd[18296]: check_control: Received out of order control packet on tunnel -1 (got 1, expected 0)
Mar 27 09:31:25  daemon.debug xl2tpd[18296]: handle_packet: bad control packet!
Mar 27 09:31:27  daemon.notice xl2tpd[18296]: Maximum retries exceeded for tunnel 42851.  Closing.
Mar 27 09:31:27  daemon.info xl2tpd[18296]: Connection 43565 closed to X.X.X.X, port 51277 (Timeout)
Mar 27 09:31:27  daemon.debug xl2tpd[18296]: Unable to deliver closing message for tunnel 22743. Destroying anyway.
Mar 27 09:31:27  daemon.debug xl2tpd[18296]: check_control: Received out of order control packet on tunnel -1 (got 1, expected 0)
Mar 27 09:31:27  daemon.debug xl2tpd[18296]: handle_packet: bad control packet!
Mar 27 09:31:27  daemon.debug xl2tpd[18296]: check_control: Received out of order control packet on tunnel -1 (got 4, expected 0)
Mar 27 09:31:27  daemon.debug xl2tpd[18296]: handle_packet: bad control packet!
Mar 27 09:31:27  daemon.debug xl2tpd[18296]: check_control: Received out of order control packet on tunnel -1 (got 3, expected 0)
Mar 27 09:31:27  daemon.debug xl2tpd[18296]: handle_packet: bad control packet!
Mar 27 09:31:27  daemon.debug xl2tpd[18296]: check_control: Received out of order control packet on tunnel -1 (got 1, expected 0)
Mar 27 09:31:27  daemon.debug xl2tpd[18296]: handle_packet: bad control packet!

logs client side:

Mar 27 10:15:32  xl2tpd[10164]: Maximum retries exceeded for tunnel 45747.  Closing. 
Mar 27 10:15:32  xl2tpd[10164]: Connection 0 closed to X.X.X.X, port 1701 (Timeout) 
Mar 27 10:15:33  xl2tpd[10164]: Can not find tunnel 8305 (refhim=0) 
Mar 27 10:15:33  xl2tpd[10164]: Can not find tunnel 8382 (refhim=0) 
Mar 27 10:15:35  xl2tpd[10164]: Can not find tunnel 8305 (refhim=0) 
Mar 27 10:15:37  xl2tpd[10164]: Can not find tunnel 8305 (refhim=0) 
Mar 27 10:15:37  xl2tpd[10164]: Will redial in 2 seconds 
Mar 27 10:15:39  xl2tpd[10164]: Can not find tunnel 8305 (refhim=0) 
Mar 27 10:15:39  xl2tpd[10164]: Connecting to host X.X.X.X, port 1701 
Mar 27 10:15:41  xl2tpd[10164]: Can not find tunnel 8305 (refhim=0) 
Mar 27 10:15:44  xl2tpd[10164]: Maximum retries exceeded for tunnel 19235.  Closing. 
Mar 27 10:15:44  xl2tpd[10164]: Connection 0 closed to X.X.X.X, port 1701 (Timeout) 
Mar 27 10:15:45  xl2tpd[10164]: Can not find tunnel 8305 (refhim=0) 
Mar 27 10:15:47  xl2tpd[10164]: Can not find tunnel 52351 (refhim=0) 
Mar 27 10:15:47  xl2tpd[10164]: Can not find tunnel 8305 (refhim=0) 
Mar 27 10:15:49  xl2tpd[10164]: Will redial in 2 seconds 
Mar 27 10:15:49  xl2tpd[10164]: Can not find tunnel 52351 (refhim=0) 
Mar 27 10:15:49  xl2tpd[10164]: Can not find tunnel 8305 (refhim=0) 
Mar 27 10:15:51  xl2tpd[10164]: Connecting to host X.X.X.X, port 1701 
Mar 27 10:15:51  xl2tpd[10164]: Can not find tunnel 52351 (refhim=0) 
Mar 27 10:15:56  xl2tpd[10164]: Maximum retries exceeded for tunnel 50529.  Closing. 
Mar 27 10:15:56  xl2tpd[10164]: Connection 0 closed to X.X.X.X, port 1701 (Timeout) 
Mar 27 10:15:57  xl2tpd[10164]: Can not find tunnel 52351 (refhim=0) 
Mar 27 10:15:59  xl2tpd[10164]: Can not find tunnel 52351 (refhim=0) 
Mar 27 10:16:01  xl2tpd[10164]: Will redial in 2 seconds 
Mar 27 10:16:01  xl2tpd[10164]: Can not find tunnel 52351 (refhim=0) 
Mar 27 10:16:03  xl2tpd[10164]: Connecting to host X.X.X.X, port 1701 
Mar 27 10:16:03  xl2tpd[10164]: Can not find tunnel 52351 (refhim=0) 
Mar 27 10:16:05  xl2tpd[10164]: Can not find tunnel 55323 (refhim=0) 
Mar 27 10:16:05  xl2tpd[10164]: Can not find tunnel 52351 (refhim=0) 
Mar 27 10:16:05  xl2tpd[10164]: Can not find tunnel 55323 (refhim=0)

what would be the problem?

**Comment by PascalRD** [comment]
We have the same problem.

**Comment by technimad** [comment]
I resolved it by using a more recent version of xl2tpd.


Op 26 mrt. 2015 om 10:08 heeft Pavel <notifications@github.com> het
volgende geschreven:

We have the same problem.

—
Reply to this email directly or view it on GitHub
<https://github.com/xelerance/xl2tpd/issues/40#issuecomment-86416115>.

**Comment by PascalRD** [comment]
thx

**Comment by PascalRD** [comment]
thanks a lot, version 1.3.6 works fine
