### ISSUE TITLE
xl2tpd 1.3.1 send out huge mount of data when connecting

### ISSUE THREAD

**Issue by yaskeryang** [xelerance/xl2tpd#42]
Don't know if I hit a bug or it just configuration file error. When I try to connect a Linux road warrior(openswan + xl2tpd + pppd) to a linux VPN server(openswan + xl2tpd + pppd, Debian 7.0), xl2tpd in the server side seems freezing, and take a large amount of CPU time to send out packets.

And it generate endless tcpdump like this(which client try to ping the server, which become unsuccess later):

00:48:18.791170 IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1 > 10.223.195.113: ip-proto-17}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}
00:48:18.791186 IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP truncated-ip - 16 bytes missing! 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1.1701 > 10.223.195.113.1701:  l2tp:[](64610/20812) {IP 10.1.2.1 > 10.223.195.113: ip-proto-17}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}

I don't understand what's happened. OpenSwan in fact works well, and ipsec tunnel is already established.  This happened when client try to connect(by using echo "c server" > l2tp_control), then try to ping vpn server(using VPN gateway ip, 10.1.2.1 shows above), then xl2tpd seems go crazy...

And with the same configuration file, if Linux client is behind NAT, it works well.

And if I use a Windows machine to connect server directly(not behind nat), it works well too.

Ipsec client version: Linux Openswan U2.6.32/K2.6.18-194.el5 (netkey)
Ipsec server version: Linux Openswan U2.6.37/K3.2.0-4-686-pae (netkey)
xl2tpd client version: 1.3.1(some rpm for CentOS).
xl2tpd server version: 1.3.1(Debian stable)
pppd client version: pppd version 2.4.4
pppd server version: pppd version 2.4.5

**Comment by shussain** [comment]
1.3.1 is super old. Closing this issue
