### ISSUE TITLE
xl2td fails to accept connections on simultanious reconnect of multiple clients

### ISSUE THREAD

**Issue by technimad** [xelerance/xl2tpd#48]
Hi,

I have a VPN server running xl2tpd 1.3.1+dfsg-1ubuntu0.12.04.1 on Ubuntu 12.04.4
Around 30 clients connect to this server at any given time. The clients run the l2tp client in RouterOS 5.26.

When the network connectivity between the clients and the server gets disrupted, causing all clients to disconnect at the same time and all trying to reconnect at a later point in time. The clients cannot establish a connection to the xl2tpd server. However, when not all (approx. 30) clients try to reconnect, but this number is lowered to a few (exact number unknown tried with 5) by an intermediate firewall, the clients that are allowed through the firewall reconnect fine. (without any restart or reconfiguration of the xl2tpd server/service). The subsequent clients can only establish their connection when they are allowed in the intermediate firewall by small numbers at a time.

It looks like xl2tpd, with my configuration, cannot handle the simultanious (re)connect of a larger number of clients.

The config:
/etc/xl2tpd/xl2tpd.conf:

[global]
[lns default]
ip range = 172.17.255.2-172.17.255.127
local ip = 172.17.255.1
refuse chap = yes
refuse pap = yes
require authentication = yes
ppp debug = yes
pppoptfile = /etc/ppp/options.xl2tpd
length bit = yes

/etc/ppp/options.xl2tpd:

asyncmap 0
auth
crtscts
lock
hide-password
modem
+chap
name l2tpd
lcp-echo-interval 15
lcp-echo-failure 4
noipx

The failing (re)connects are still happening after 4 times the lcp-echo-interval. The errors given in the logs are numerous (because of the high number of clients). I'll give some examples of the logs at the moment of the failure of the reconnects:

xl2tpd[19464]: Connection 2571 closed to 10.2.49.5, port 1701 (Timeout)
xl2tpd[19464]: Unable to deliver closing message for tunnel 65088. Destroying anyway.
xl2tpd[19464]: Maximum retries exceeded for tunnel 26162.  Closing.
xl2tpd[19464]: Connection 143 closed to 192.168.2.12, port 1701 (Timeout)
xl2tpd[19464]: Unable to deliver closing message for tunnel 3977. Destroying anyway.
xl2tpd[19464]: control_finish: Peer requested tunnel 462 twice, ignoring second one.
xl2tpd[19464]: Can not find tunnel 4123 (refhim=0)
xl2tpd[19464]: network_thread: unable to find call or tunnel to handle packet.  call = 0, tunnel = 4123 Dumping.
xl2tpd[19464]: Can not find tunnel 4123 (refhim=0)
Sep  9 16:34:13 winzsv028 xl2tpd[19464]: control_finish: Peer requested tunnel 177 twice, ignoring second one.
Sep  9 16:34:13 winzsv028 xl2tpd[19464]: control_finish: Peer requested tunnel 25 twice, ignoring second one.
Sep  9 16:34:15 winzsv028 xl2tpd[19464]: Maximum retries exceeded for tunnel 18834.  Closing.
Sep  9 16:34:15 winzsv028 xl2tpd[19464]: Connection 185 closed to 192.168.21.138, port 1701 (Timeout)
Sep  9 16:34:15 winzsv028 xl2tpd[19464]: Unable to deliver closing message for tunnel 26162. Destroying anyway.
xl2tpd[19464]: Can not find tunnel 21810 (refhim=0)
xl2tpd[19464]: network_thread: unable to find call or tunnel to handle packet.  call = 0, tunnel = 21810 Dumping.
xl2tpd[19464]: Maximum retries exceeded for tunnel 39381.  Closing.
xl2tpd[19464]: Connection 177 closed to 192.168.8.12, port 1701 (Timeout)
xl2tpd[19464]: Unable to deliver closing message for tunnel 54780. Destroying anyway.
xl2tpd[19464]: Can not find tunnel 24225 (refhim=0)
xl2tpd[19464]: network_thread: unable to find call or tunnel to handle packet.  call = 0, tunnel = 24225 Dumping.
xl2tpd[19464]: control_finish: Peer requested tunnel 177 twice, ignoring second one.
xl2tpd[19464]: Can not find tunnel 41097 (refhim=0)
xl2tpd[19464]: network_thread: unable to find call or tunnel to handle packet.  call = 0, tunnel = 41097 Dumping.
xl2tpd[19464]: Can not find tunnel 32549 (refhim=0)

When clients do connect the expected is logged:

xl2tpd[1702]: Connection established to 192.168.8.4, 1701.  Local: 38966, Remote: 147 (ref=0/0).  LNS session is 'default'
xl2tpd[1702]: check_control: Received out of order control packet on tunnel 147 (got 3, expected 2)
xl2tpd[1702]: handle_packet: bad control packet!
xl2tpd[1702]: start_pppd: I'm running: 
xl2tpd[1702]: "/usr/sbin/pppd" 
xl2tpd[1702]: "passive" 
xl2tpd[1702]: "nodetach" 
xl2tpd[1702]: "172.17.255.1:172.17.255.2" 
xl2tpd[1702]: "refuse-pap" 
xl2tpd[1702]: "refuse-chap" 
xl2tpd[1702]: "auth" 
xl2tpd[1702]: "debug" 
xl2tpd[1702]: "file" 
xl2tpd[1702]: "/etc/ppp/options.xl2tpd" 
xl2tpd[1702]: "ipparam" 
xl2tpd[1702]: "192.168.8.4" 
xl2tpd[1702]: "/dev/pts/0" 
xl2tpd[1702]: Call established with 192.168.8.4, Local: 11799, Remote: 1, Serial: 0
xl2tpd[1702]: Connection established to 192.168.1.10, 1701.  Local: 61166, Remote: 341 (ref=0/0).  LNS session is 'default'
xl2tpd[1702]: start_pppd: I'm running: 
xl2tpd[1702]: "/usr/sbin/pppd" 
xl2tpd[1702]: "passive" 
xl2tpd[1702]: "nodetach" 
xl2tpd[1702]: "172.17.255.1:172.17.255.3" 
xl2tpd[1702]: "refuse-pap" 
xl2tpd[1702]: "refuse-chap" 
xl2tpd[1702]: "auth" 
xl2tpd[1702]: "debug" 
xl2tpd[1702]: "file" 
xl2tpd[1702]: "/etc/ppp/options.xl2tpd" 
xl2tpd[1702]: "ipparam" 
xl2tpd[1702]: "192.168.1.10" 
xl2tpd[1702]: "/dev/pts/3" 
xl2tpd[1702]: Call established with 192.168.1.10, Local: 8545, Remote: 1, Serial: 20

Is my config causing this behaviour, or does it point to a bug in xl2tpd?

**Comment by shussain** [comment]
Varius users (in comment #40) found that using newer version of xl2tpd resolves this issue
