### ISSUE TITLE
xl2tpd seg fault when using klips/mast with ipsec saref = yes

### ISSUE THREAD

**Issue by mahotz** [xelerance/xl2tpd#49]
In udp_xmit, this line is wrong:
    char cbuf[CMSG_SPACE(sizeof (unsigned int) + sizeof (struct in_pktinfo))];
It should be:
    char cbuf[CMSG_SPACE(sizeof (unsigned int) + CMSG_SPACE(sizeof (struct in_pktinfo)))];

With insufficient space in cbuf for the two control messages (IP_PKTINFO and IP_IPSEC_REFINFO) the call to CMSG_NXTHDR returns null.

xl2tpd[6717]: control_finish: sending SCCRP
xl2tpd[6717]: trying to send control packet to 28156
xl2tpd[6717]: control_xmit: Scheduling and transmitting packet 0
xl2tpd[6717]: sending with saref=9 using sarefnum=30

Program received signal SIGSEGV, Segmentation fault.
0x0000000000411785 in udp_xmit (buf=0x6253e0, t=0x626b40) at network.c:325
325             cmsg->cmsg_level = IPPROTO_IP;

**Comment by swplotner** [comment]
Thank you for the patch thoughts above. I have worked my way through that (i.e. the errors you saw, I also got to see and I applied your patches step by step) and in the end I get:

xl2tpd[17567]: network_thread: recv packet from 10.1.10.12, size = 105, tunnel = 0, call = 0 ref=10 refhim=9
xl2tpd[17567]: get_call: allocating new tunnel for host 10.1.10.12, port 1701.
xl2tpd[17567]: sending with saref=9 using sarefnum=30
xl2tpd[17567]: network_thread: select timeout
xl2tpd[17567]: sending with saref=9 using sarefnum=30
xl2tpd[17567]: network_thread: select timeout
xl2tpd[17567]: sending with saref=9 using sarefnum=30
xl2tpd[17567]: network_thread: select timeout
xl2tpd[17567]: sending with saref=9 using sarefnum=30
xl2tpd[17567]: network_thread: select timeout
xl2tpd[17567]: sending with saref=9 using sarefnum=30
xl2tpd[17567]: network_thread: select timeout
xl2tpd[17567]: Maximum retries exceeded for tunnel 21993.  Closing.
xl2tpd[17567]: sending with saref=9 using sarefnum=30
xl2tpd[17567]: Connection 250 closed to 10.1.10.12, port 1701 (Timeout)
xl2tpd[17567]: network_thread: select timeout
xl2tpd[17567]: sending with saref=9 using sarefnum=30
xl2tpd[17567]: network_thread: select timeout
xl2tpd[17567]: sending with saref=9 using sarefnum=30
xl2tpd[17567]: network_thread: recv packet from 10.1.10.12, size = 105, tunnel = 0, call = 0 ref=10 refhim=9
xl2tpd[17567]: get_call: allocating new tunnel for host 10.1.10.12, port 1701.
xl2tpd[17567]: control_finish: Peer requested tunnel 250 twice, ignoring second one.

I keep getting the "requested tunnel ... twice" problem.

Would you mind posting the complete xl2tpd source or just that file with your pathces in it?

Steffen
