### ISSUE TITLE
xl2tpd.service

### ISSUE THREAD

**Issue by glixx** [xelerance/xl2tpd#50]
``` diff
[Unit]
Description=Level 2 Tunnel Protocol Daemon (L2TP)
After=syslog.target network.target
After=ipsec.service
# Some ISPs in Russia use l2tp without IPsec, so don't insist anymore
#Wants=ipsec.service

[Service]
Type=simple
PIDFile=/var/run/xl2tpd/xl2tpd.pid
ExecStart=/usr/sbin/xl2tpd -D
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

**Comment by shussain** [comment]
We don't have xl2ptd.service

**Comment by alexl000** [comment]
xl2tpd should use systemd instead of initscript.

**Comment by shussain** [comment]
@alexl000 I don't disagree that there should be systemd options.

My original read of the ticket with the comment "Some ISPs in Russia use l2tp without IPsec, so don't insist anymore" was that someone had made changes to their xl2tpd.service and was asking us to comment it out.  I had assumed they had modified their distro's xl2tpd.service and was trying to offer it upstream.

Upon reflection, it might be that someone was offering us an xl2tpd.service

**Comment by shussain** [comment]
Reopening this ticket but I am still hesitant to replace initscript since it would impact embeded systems a lot more. 

Perhaps, a conditional flag would be better.. so that people who want to have the service, they can get that installed. But I think we should still have initscript for older systems... atleast until systemd gains more traction there (if it ever does)

**Comment by alexl000** [comment]
Yes, a conditional flag is good solution.

**Comment by shussain** [comment]
Refer to #51 for tmpfile for systemd

**Comment by wjt** [comment]
If you ship both the init script and the systemd unit, then on systemd systems the systemd unit will be used, and on non-systemd systems the init script will be used. I don't think any build-time condition is needed.

This would be useful for us in Endless OS (based on Debian Bullseye). We have xl2tpd installed for use by the NetworkManager plugin, but we do not want it to be launched by default. However, when [systemd-sysv-generator](https://www.freedesktop.org/software/systemd/man/systemd-sysv-generator.html) parses the init script, it parses the LSB header:

```
# Default-Start:     2 3 4 5
```

and based on this enables the service by default for `multi-user.target` (corresponding to runlevels 2, 3, 4) and `graphical.target` (corresponding to runlevel 5). We normally use the [systemd.preset](https://www.freedesktop.org/software/systemd/man/systemd.preset.html) mechanism to disable unwanted services but this does not work for units generated and enabled by the systemd-sysv-generator...
