### ISSUE TITLE
Connection loss at large data transfers

### ISSUE THREAD

**Issue by skyh** [xelerance/xl2tpd#54]
This issue corresponding to xl2tpd v.1.3.1 on Debian. My provider uses L2TP protocol with no security layer. I use xl2tpd for LAC connection. On large file transfers xl2tpd loss connection and I see this messages when tunnel debugging enabled:

```
Jan 15 17:16:33 banka xl2tpd[7363]: handle_packet: unable to expand payload!
Jan 15 17:16:33 banka xl2tpd[7363]: network_thread: bad packet
Jan 15 17:16:33 banka xl2tpd[7363]: handle_packet: unable to expand payload!
Jan 15 17:16:33 banka xl2tpd[7363]: network_thread: bad packet
Jan 15 17:16:33 banka xl2tpd[7363]: handle_packet: unable to expand payload!
Jan 15 17:16:33 banka xl2tpd[7363]: network_thread: bad packet
```

after this, pppd terminating with messages

```
Jan 15 17:16:35 banka pppd[7364]: No response to 2 echo-requests
Jan 15 17:16:35 banka pppd[7364]: Serial link appears to be disconnected.
Jan 15 17:16:35 banka pppd[7364]: Connect time 0.7 minutes.
Jan 15 17:16:35 banka pppd[7364]: Sent 400988 bytes, received 6614244 bytes.
Jan 15 17:16:35 banka pppd[7364]: restoring old default route to eth0 [172.20.162.1]
Jan 15 17:16:35 banka pppd[7364]: Script /etc/ppp/ip-down started (pid 7378)
Jan 15 17:16:35 banka pppd[7364]: sent [LCP TermReq id=0x2 "Peer not responding"]
Jan 15 17:16:35 banka pppd[7364]: Script /etc/ppp/ip-down finished (pid 7378), status = 0x0
...
Jan 15 17:16:37 banka pppd[7364]: Terminating on signal 15
Jan 15 17:16:37 banka pppd[7364]: Modem hangup
Jan 15 17:16:37 banka pppd[7364]: Connection terminated.
Jan 15 17:16:37 banka pppd[7364]: Exit.
```

Subsequently xl2tpd reconnects and everything works fine until next download attempt.

There is forum page (in Russan) where similar behaviour described http://forum.nag.ru/forum/index.php?showtopic=81838

The problem was fixed by adding `set l2tp disable dataseq` in provider's server `mpd.conf`. May be this info can help.

Interesting note: "bad packets" was captured and analyzed in Wireshark without any problems or warnings.

Windows 7 and Mac OS 10.10 l2tp clients works fine with same provider.

**Comment by shussain** [comment]
Closing this issue but #133 had some interesting observations on it
