### ISSUE TITLE
xl2tpd 1.3.6 looping - with possible fix included [patch]

### ISSUE THREAD

**Issue by divereigh** [xelerance/xl2tpd#55]
I have found that xl2tpd will occasionally go into an endless loop. It seems to be when the recvmsg in network.c gets a error 113 (EHOSTUNREACH). I get this message in the syslog:-

xl2tpd[3735]: network_thread: recvfrom returned error 113 (No route to host)

At which point xl2tpd goes into an endless loop, calling recvmsg and getting EAGAIN - according to strace on the process.

We have been running the same version on Centos 6.4 for over a year without this problem, however it has cropped up since moving to another server running Centos 7. In both cases we are using it as a LNS (server).

From what I understand EHOSTUNREACH is normally a fairly transient error (probably network related) and may not even be related to the current fd that is being read. The problem is that xl2tpd loops back round and tries to do another (non blocking) readmsg from the same fd. However because there is nothing there gets an EAGAIN and so tries again.

I think the fix (but I am not an expert in the code) is to move onto the next fd on any error including EAGAIN, just as it does when it successfully reads from the fd. I note that the code does handle ECONNREFUSED and EBADF properly (closes the fd and marks it). However no other error codes. I originally just changed it to handle EHOSTUNREACH in the same way, however that really doesn't deal with any other error code that could crop up.

Here's the proposed fix:

```
*** xl2tpd-5619e1771048e74b729804e8602f409af0f3faea-orig/network.c      2014-01-16 07:58:37.000000000 +1100
--- xl2tpd-5619e1771048e74b729804e8602f409af0f3faea/network.c   2015-02-01 05:26:39.288902130 +1100
***************
*** 545,550 ****
--- 545,551 ----
                      l2tp_log (LOG_WARNING, "%s: received too small a packet\n",
                           __FUNCTION__);
                  }
+               if (st) st=st->next;
                continue;
              }

```

**Comment by shussain** [comment]
Code added in commit 4c98ab5e06f3d5174d9abff75e4707e437dd2095
