### ISSUE TITLE
error in tag

### ISSUE THREAD

**Issue by howlett** [xelerance/xl2tpd#65]
Since git 2.1, there have been a number of new fsck options added which produce issues when I clone the repository.

$ git fsck --full
Checking object directories: 100% (256/256), done.
error in tag 94d33c6a0ec2b88f191f837a1b031e2d56f254ef: unterminated header
error in tag 57f4014f50a005a6aaf249b8eef654e036585f7f: unterminated header
error in tag 3600562b59a70413634947e0e5b872fb84f0f88e: unterminated header
error in tag b6fff94364c507be954ec68d8924cd20202034d6: unterminated header
error in tag d2ee8be4e80085cc79f5cce932903c773bbdf6a4: unterminated header
error in tag 12301acd438d1d4255e8011f073cf5433d461d35: unterminated header
Checking objects: 100% (1746/1746), done.

These new tests are enabled by default when using git fsck.  I have been testing with git version 2.4.4.409.g5b1d901 and thought you might want to know so the error/warning messages can be corrected.

**Comment by shussain** [comment]
Closing since git 2.7.4 doesn't produce this issue.
