### ISSUE TITLE
DNS leaking

### ISSUE THREAD

**Issue by kureikain** [xelerance/xl2tpd#70]
Hi,

We use libreswan and xl2tpd. We pushed DNS from xl2tpd using `ms-dns`. On Mac OSX, using Mac built-in client, after connecting, the DNS queries are sent to our DNS server. 

However, sometime we see the DNS queries are send to original DNS of wifi connection instead of going into our DNS. 

We returned two DNSs at a time so it's very rare that our DNS is down, during the very same time, other client use DNS totally fine. Then after some seconds or some minutes, the system started to send DNS query to our DNS server again.

We used `scutil` to confirm that our DNS which are pushed from VPN connection is the first resolver:

```
scutil --dns
DNS configuration

resolver #1
  nameserver[0] : our_dns_1_ip
  nameserver[1] : our_dns_2_ip
  if_index : 4 (en0)
  flags    : Request A records, Request AAAA records
  reach    : Reachable
```

**Comment by shussain** [comment]
Hello,

Thank you for the writing this ticket and using xl2tpd

I must admit I am slightly confused. if you are using the Mac built-in client, and occasionally you are getting DNS queries sent to the DNS of your wifi connection, is that not an issue with the Mac built-in L2TP client? 

Perhaps I misunderstood?

**Comment by kureikain** [comment]
@shussain Yes, that must be something related to the OS itself other than xl2tpd.

I just ran out of options to debug this system and it never happen on my mac...So I posted here in a hope someone can give me some hints to debug this problem.
