### ISSUE TITLE
Cannot connect using stock Android 5.1.1 on Nexus 6 phone

### ISSUE THREAD

**Issue by mgperkow** [xelerance/xl2tpd#74]
I'm running xl2tpd 1.3.6 with ipsec-tools 0.82 (racoon) as the IKE daemon. No problems with Windows clients connecting, but my Android phone cannot connect. Here's an appropriately redacted sample of the syslogs I've collected while trying to get it working:

Sep 10 07:55:09 xxxxxx xl2tpd[32626]: Maximum retries exceeded for tunnel 50215.  Closing.
Sep 10 07:55:09 xxxxxx xl2tpd[32626]: Connection 41227 closed to xxx.xxx.xxx.xxx, port 55731 (Timeout)
Sep 10 07:55:19 xxxxxx xl2tpd[32626]: Maximum retries exceeded for tunnel 13037.  Closing.
Sep 10 07:55:19 xxxxxx xl2tpd[32626]: Connection 41227 closed to xxx.xxx.xxx.xxx, port 55731 (Timeout)

Similar pairs of messages will appear in the log about every 10-20 seconds until the Android client eventually gives up. I've tried various configuration tweaks (just about everything I could think of) without any success or even apparent effect on the issue.

I've heard that the Android VPN client is rather buggy in general, but I also see messages here and there about some apparently getting some combination to work now and then. I'm hoping there's some kind of solution out there (or one that can be achieved).

Not necessarily relevant here, but I _have_ gotten the Android connection to work in the past using openl2tp 1.8, although I'm trying to move away from that software since it's becoming harder to maintain its functionality on my machine as some of its dependent libraries are replaced by newer versions, which are starting to drop some of the older style functionality openl2tp needs...

**Comment by mcr** [comment]
Unless your phone is rooted and you can get debugging out of the client, I doubt it will be easy to diagnose this.  You could probably increase the logging level in the xl2tp, and maybe that would reveal some obvious issue.  

If you are using racoon for your IPsec, and your android is behind a NAT (are the windows behind at NAT?), then how do you deal with duplicate IP addresses?

openl2tp did a lot more work at interop; but in general that means that they have worked around buggy implementations; the openl2tp work became prol2tp, and you may be better off to use that if you can afford a support license.

**Comment by mcr** [comment]
oh, and Android doesn't need L2TP to make connections anymore.

**Comment by mgperkow** [comment]
I agree it's a pretty tough one, and I'm not surprised that you also figure it would be tough to diagnose. From what I can tell, Android isn't "liking" some response it's getting during the L2TP setup, and so it repeats the request until it finally gives up.

Duplicate IPs are a conceivable issue, but the scope of my VPN implementation is limited enough that it doesn't present a problem in practice.

Ah, I actually hadn't been aware that openl2tp had since been ported into another application. I might have to look into that.

Are you referring to the "Hybrid RSA" mode that I see in Android's VPN configuration? I honestly don't know much about that and so hadn't given it much thought, but I'm starting to read about it now, so perhaps it will give me another avenue to proceed.

Your responses have given me some additional ideas and are appreciated. Thank you.

**Comment by mgperkow** [comment]
Alright, for any who might be interested, I managed to get the Android part of my VPN working with Android's IPSec Hybrid RSA support (which requires only racoon on the server end in this case), and xl2tpd handles the L2TP/IPSec Windows connections just fine, so my "issue" can pretty much be considered moot *per se* from my own perspective. So, while xl2tpd doesn't seem to work with Android for L2TP/IPSec, I'm pretty sure Android itself is to blame rather than xl2tpd. I would say feel free to close this issue report if you wish as it is most likely not actually a bug with xl2tpd itself.
