### ISSUE TITLE
RFC states retransmissions MUST employ exponential backoff

### ISSUE THREAD

**Issue by Climax777** [xelerance/xl2tpd#76]
Currently the daemon doesn't obey the following requirement as seen at https://www.rfc-editor.org/rfc/rfc2661.txt: 

Each subsequent retransmission of a message MUST employ an exponential backoff interval

**Comment by Climax777** [comment]
Please check my PR :smile:

**Comment by shussain** [comment]
Thank you for your commit. We will be testing your pull request soon.
