### ISSUE TITLE
Debian Jessie xl2tpd crashes after a few minute. Error: xl2tpd[2414]: segfault at 188 ip

### ISSUE THREAD

**Issue by stanleyli60** [xelerance/xl2tpd#85]
Dear developers,

I am trying to setup xl2tpd in Debian Jessie using xl2tpd v1.3.6. However, it crashes after a few minutes. 

I am having xl2tpd[2414]: segfault at 188 ip error message. This is the same issue as reported in the following urls:
https://bugs.launchpad.net/ubuntu/+source/xl2tpd/+bug/1509183
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=760602

How can I fix this issue?

Thanks in advance,
Stanley

**Comment by yousong** [comment]
The devel branch here contains several memory access related fixes (https://github.com/xelerance/xl2tpd/pull/77, https://github.com/xelerance/xl2tpd/pull/69), you can give them a try.

**Comment by stanleyli60** [comment]
Thanks for the reply. I will give it a try tonight or tomorrow.

**Comment by shussain** [comment]
Hello, 
  Did you get a chance to look at the branch? Is your issue still occurring?

Samir

**Comment by stanleyli60** [comment]
Sorry, I forgot to comment back. It is working with the current version. Thanks.

**Comment by kooky** [comment]
I swapped to use the package from Debian backports.  So far has been running about 1 week without stopping.  Much better.

https://packages.debian.org/jessie-backports/xl2tpd
