### ISSUE TITLE
How to deny connections to xl2tp without ipsec encryption?

### ISSUE THREAD

**Issue by truongtx8** [xelerance/xl2tpd#97]
Hi all,
Sorry for posting my question here since I can't find anyway to contact xl2tpd team.

I've successful setup xl2tp with strongswan for my L2TP/IPSec VPN server. My problem is, clients can still connect to xl2tpd without IPSec encryption.

Is it possible to deny/drop connection to xl2tpd without encryption?

Thanks and best regards,
Truong.

**Comment by simondeziel** [comment]
You can use the iptables policy module like this:

iptables -A INPUT -p udp --dport 1701 -m policy --dir in --pol ipsec -j ACCEPT
iptables -A INPUT -p udp --dport 1701 -j DROP

**Comment by truongtx8** [comment]
iptables is what I'm looking for. Thank you so much.

**Comment by chaiken-verticloud** [comment]
When using the KLIPS protostack, iptables filtering by policy does not work.  When using KLIPS, filtering inbound traffic by interface works.  For example, if eth0 is the external interface, this rule denies unencrypted L2TP traffic:

```
iptables -A INPUT -p udp -i eth0 --dport 1701 --jump DROP
```
